- README.md
- lib/generators/rails/mobility/translations_generator.rb
The readme is currently hard to understand for people who don't know much about content translation strategies, etc (and even for people who do). This is my attempt to improve that.
> Restructure readme to make it more understandable

- lib/mobility/backend/active_record/key_value.rb
- lib/mobility/backend/sequel/key_value.rb
- spec/mobility/backend/active_record/key_value_spec.rb
- spec/mobility/backend/sequel/key_value_spec.rb
This is a small but important change to ensure data integrity. When you translate a model using the KeyValue backend with some attribute, say `title`, then later decide to change the name of the attribute to something else, your earlier translations will disappear. This is natural since they were stored with the key `title`, and Mobility is now looking for a different key on the association.
This means that if you change your attribute name *back*, those earlier translations will again become available, because they were never destroyed (the change of attribute name was made at the code level, not the data level). I consider this a good thing.
However, currently they will also remain in the db even after you *destroy* the model, although translations with keys currently defined on the …
> Destroy all translations after model is destroyed (KeyValue backend)

- lib/mobility.rb
- lib/mobility/attributes.rb
- lib/mobility/fallthrough_accessors.rb
- lib/mobility/instance_methods.rb
- lib/mobility/locale_accessors.rb
- lib/mobility/sequel/column_changes.rb
- spec/mobility/attributes_spec.rb
This removes the private `mobility_get`, `mobility_set` and `mobility_present?` instance methods, which are not needed anymore now that the presence filtering has been extracted into its own module (in 7d6547).
Instead of overriding `mobility_set`, the `Mobility::Sequel::ColumnChanges` module now overrides setter methods directly, which is cleaner anyway.
> Refactor instance methods

- Gemfile
- lib/mobility/active_record.rb
- lib/mobility/active_record/uniqueness_validator.rb
- spec/mobility/backend/active_record/column_spec.rb
- spec/mobility/backend/active_record/hstore_spec.rb
- spec/mobility/backend/active_record/jsonb_spec.rb
- spec/mobility/backend/active_record/key_value_spec.rb
- spec/mobility/backend/active_record/table_spec.rb
- spec/support/helpers.rb
- spec/support/shared_examples/validation_examples.rb
This adds a `Mobility::ActiveRecord::UniquenessValidator` that is defined as a subclass on a model namespace when the model includes `Mobility`. By doing this, the model will use this validator if `validates` is called with `uniqueness: true`, but due to the namespacing the validator will not be used for any other (non-translated) models.
I'm conciously avoiding monkey-patching the original uniqueness validator since that could have strange and unpredictable results. The validator defined here sticks to very simple queries using `where` and `not` in order to be compatible with *any* supported backend.
Fixes #20
> Handle uniqueness validation for translated attributes and translated scopes

- lib/mobility/backend/active_record/key_value.rb
`DEPRECATION WARNING: Passing a class to the class_name is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: has_many :mobility_text_translations, class_name: 'Mobility::ActiveRecord::TextTranslation'`
> Fix deprecation in has_many associations

- lib/generators/rails/mobility/active_record_migration_compatibility.rb
- lib/generators/rails/mobility/backend_generators/base.rb
- lib/generators/rails/mobility/generators.rb
- lib/generators/rails/mobility/install_generator.rb
- lib/generators/rails/mobility/templates/column_translations.rb
- lib/generators/rails/mobility/templates/create_string_translations.rb
- lib/generators/rails/mobility/templates/create_text_translations.rb
- lib/generators/rails/mobility/templates/table_migration.rb
- lib/generators/rails/mobility/templates/table_translations.rb
- spec/generators/rails/mobility/install_generator_spec.rb
- spec/generators/rails/mobility/translations_generator_spec.rb
I looked at which tests where failing on the `active_record_4.2` branch, and thought I'd try to help out where I could.
This should fix the failing generator tests on Rails 4.2.
- This [seems to be](https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/rails/generators/active_record/migration.rb#L19-L22) used to add `id: :uuid` and similar
- AFAIK there's no Rails 4.2 equivalent, so we can just leave it out
- I'm guessing this is for the new `has_secure_token` attributes
- Again, it shouldn't need any 4.2 counterpart
Let me know what you think. :)
> Make generators work with Rails 4.2

- .travis.yml
- lib/mobility.rb
- lib/mobility/active_model.rb
- lib/mobility/active_record.rb
- lib/mobility/active_record/attribute_methods.rb
- lib/mobility/backend/active_record.rb
- lib/mobility/backend/active_record/dirty.rb
- lib/mobility/backend/dirty.rb
- spec/mobility/active_record/attribute_methods_spec.rb
- spec/mobility/backend/active_record/dirty_spec.rb
There are tons of deprecation warnings currently in Rails/AR 5.1. This removes the warnings while still passing specs. However, it introduces some questionable changes to achieve this.
There are two problems:
1. AR::Dirty now requires you to declare all attributes upfront rather than in an open-ended way with `attr_will_change!` (see rails/rails#27963). To get around this, I've overridden `has_attribute?` to make locale accessors (`title_en` etc) act like real attributes. We can't actually define them all since the list of locales is open-ended.
2. You can't call `changes` from within after save callbacks. This conflicts with code used to support `previous_changes` in the Mobility Dirty backend module. This is fixed using a `before_save` hook rather than a `changes_applied` override, but …
> Fix deprecation warnings in Rails 5.1

- README.md
- lib/mobility/attributes.rb
- lib/mobility/backend.rb
- lib/mobility/backend/default.rb
- spec/mobility/attributes_spec.rb
- spec/mobility/backend/default_spec.rb
This adds an option which can be passed when defining an attribute or when
calling an attribute reader to define a default value which will be returned if
the backend would otherwise return `nil`.
Resolves #48.
> Add option to set default value or proc for translated attribute

- lib/mobility.rb
- lib/mobility/attributes.rb
- lib/mobility/backend/cache.rb
- lib/mobility/backend/default.rb
- lib/mobility/backend/dirty.rb
- lib/mobility/backend/fallbacks.rb
- lib/mobility/backend/presence.rb
- lib/mobility/configuration.rb
- lib/mobility/fallthrough_accessors.rb
- lib/mobility/locale_accessors.rb
- lib/mobility/wrapper.rb
- spec/mobility/attributes_spec.rb
- spec/mobility/backend/cache_spec.rb
- spec/mobility/backend/default_spec.rb
- spec/mobility/backend/dirty_spec.rb
- spec/mobility/backend/fallbacks_spec.rb
- spec/mobility/backend/presence_spec.rb
- spec/mobility/wrapper_spec.rb
- spec/mobility_spec.rb
Currently there is a lot of hard-coded dependencies between options-setting in
the `Mobility::Attributes` class and the various backend modules (cache,
fallbacks, etc.), whereas these should really be independent.
I'm going to try to restructure things so that modules can be defined in such a
way that `Mobility::Attributes` does not need to explicitly know anything about
them when including them from options.
> Reorganize module options

- lib/mobility/active_model/backend_resetter.rb
- lib/mobility/backend.rb
- lib/mobility/backend/active_record/hash_valued.rb
- lib/mobility/backend/active_record/key_value.rb
- lib/mobility/backend/active_record/serialized.rb
- lib/mobility/backend/active_record/table.rb
- lib/mobility/backend/cache.rb
- lib/mobility/backend/key_value.rb
- lib/mobility/backend/sequel/hash_valued.rb
- lib/mobility/backend/sequel/key_value.rb
- lib/mobility/backend/sequel/serialized.rb
- lib/mobility/backend/sequel/table.rb
- lib/mobility/backend/serialized.rb
- lib/mobility/backend/table.rb
- lib/mobility/backend/translation_cacher.rb
- lib/mobility/backend_resetter.rb
- lib/mobility/sequel/backend_resetter.rb
- spec/mobility/backend/active_record/key_value_spec.rb
- spec/mobility/backend/active_record/serialized_spec.rb
- spec/mobility/backend/active_record/table_spec.rb
- spec/mobility/backend/cache_spec.rb
- spec/mobility/backend/sequel/key_value_spec.rb
- spec/mobility/backend/sequel/serialized_spec.rb
- spec/mobility/backend/sequel/table_spec.rb
The current code is unnecessarily complicated. This PR simplifies things so that backends can include a custom module through an `apply_module` hook. This allows KeyValue and Table backends to modify the Cache module they use just slightly to achieve the same result.
A module builder called `TranslationCacher` is shared by all cacheing strategies to cache reads; the only difference is which method is cached: in the default Cache module, `read` is cached; in KeyValue and Table backends, `translation_for` is cached (so that the translation record itself is cached, rather than the translation value).
> Refactor backend cache

- lib/mobility/backend/active_record/key_value.rb
- lib/mobility/backend/active_record/table.rb
- lib/mobility/backend/key_value.rb
- lib/mobility/backend/sequel/key_value.rb
- lib/mobility/backend/sequel/table.rb
- lib/mobility/backend/table.rb
- spec/mobility/active_record_compatibility_spec.rb
- spec/mobility/backend/active_record/key_value_spec.rb
- spec/mobility/backend/active_record/table_spec.rb
- spec/mobility/backend/sequel/key_value_spec.rb
- spec/mobility/backend/sequel/table_spec.rb
Currently the KeyValue and Table backends use association names like `mobility_string_translations` and `mobility_model_translations`, but the `mobility_` prefix is not really necessary - if for whatever reason there were a conflict in a model, the name can be changed using the `association_name` option.
This PR removes this prefix so that you don't need to type so many characters to get the model associations.
> Remove namespace from default association names

- lib/mobility/backends/active_record/table.rb
- lib/mobility/backends/sequel/table.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/backends/sequel/table_spec.rb
Rather than `model_translations`, which is what it currently is (in 0.2.0).
Globalize uses `translations` and I think it's more intuitive. Previously I was concerned about conflicts with other gems or models that may use the method `translations`, but now that Mobility has a default options configuration, anyone wanting to avoid such conflicts can simply set:
```ruby
Mobility.config.default_options = {
association_name: :my_translations
}
```
... or whatever, to avoid any possible conflict. For the vast majority of people, `post.translations` will work fine.
> Set default table backend association name to "translations"

- README.md
- lib/mobility/backend.rb
I was writing some acceptance tests when I noticed the translated fields not shown. 
I like the current behaviour where it's up to user to call `save` but the method name kind of implies writing to somewhere. So I think this small adition to docs could avoid some confusion in the future.
If you approve this change, should I also document it elsewhere? I noticed the backends each implement the `write` method so there is no one place to add it. What do you think?
> Explain write methods behaviour toards persisting translations

- lib/mobility/attributes.rb
- lib/mobility/translates.rb
- spec/mobility/attributes_spec.rb
- spec/mobility/translates_spec.rb
- spec/performance/attributes_spec.rb
Currently `Mobility::Attributes` takes a `method` argument followed by one or more attribute names, but since in 99% of cases the `method` argument is `:accessor`, it makes more sense to bump this to the keyword arguments (with a default of `method: :accessor`), and just take a list of attributes.
> Move accessor method to keyword argument in Attributes

- lib/mobility/attributes.rb
- lib/mobility/backend.rb
- lib/mobility/backends/active_record/column.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/pg_hash.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/backends/hash_valued.rb
- lib/mobility/backends/key_value.rb
- lib/mobility/backends/sequel/column.rb
- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/sequel/pg_hash.rb
- lib/mobility/backends/sequel/table.rb
- lib/mobility/backends/table.rb
- spec/mobility/backend_spec.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/sequel/key_value_spec.rb
- spec/mobility/backends/sequel/table_spec.rb
- spec/support/shared_examples/backend_examples.rb
Resolves #39.
This is a relatively small change, but an important one. Currently backends don't strictly "know" what translations they have. They only know how to query for a translation in a locale, or write to that locale.
There are many cases where you'd want to know what locales are available independent of the implementing backend, so it makes sense to add a method to get locales.
Originally I was just going to add a `locales` method which would do this, but then it occurred to me that hey, this is Ruby, so let's make it more flexible by doing it the Ruby way. So instead of defining a `locales` method, I simply defined an `each` method on every backend which yields each locale successively to a block.
In `Mobility::Backend`, I then also added a `list` method which gets the list of …
> Backends with Enumerable

- lib/mobility/plugins/fallbacks.rb
- spec/mobility/plugins/fallbacks_spec.rb
Currently passing `fallback: true` acts like `fallback: false` because `true` is interpreted as a locale rather than a boolean.
> Enable fallbacks when fallback option is true

- README.md
- lib/mobility/attributes.rb
- lib/mobility/plugins/dirty.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/fallthrough_accessors.rb
- lib/mobility/plugins/locale_accessors.rb
- spec/mobility/active_record_compatibility_spec.rb
- spec/mobility/attributes_spec.rb
- spec/mobility/plugins/active_model/dirty_spec.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
- spec/mobility/plugins/locale_accessors_spec.rb
- spec/mobility/plugins/sequel/dirty_spec.rb
- spec/performance/attributes_spec.rb
- spec/support/shared_examples/locale_accessor_examples.rb
> Disable fallbacks when using locale/fallthrough accessors

- lib/mobility/active_record/translation.rb
- lib/mobility/backends/active_record/table.rb
- spec/active_record/schema.rb
- spec/mobility/backends/active_record/column_spec.rb
- spec/mobility/backends/active_record/hstore_spec.rb
- spec/mobility/backends/active_record/jsonb_spec.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/active_record/serialized_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
- spec/support/shared_examples/cache_key_examples.rb
For the table and key_value backends, this means the model itself is touched when updating a translation.
Fixes #101. Closes #103.
> Ensure cache_key is invalidated when updating translations

- .travis.yml
- Gemfile
There are a bunch of changes coming up relating to how attributes are treated in ActiveModel and ActiveRecord. I just ran the test suite against the beta version of AR 5.2 and there are 26 failures, mostly relating to AR::Dirty.
In parallel I'm working on supporting some of the new AR::Dirty methods like `saved_changes` in #111, in response to #106, but I'm wondering if these changes will just make the transition to 5.2.0 harder. For now I'll continue on #111 but here I'm adding the latest AR versions to the build with `allow_failures`, so we can see what we will need to do to make this all work.
> Test against ActiveRecord 5.2.0.beta.x

- lib/mobility/plugins/active_record/dirty.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
> Support added AR::Dirty methods

- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/active_record/dirty.rb
> Fix AM/AR Dirty plugin issues with AR 5.2

- .travis.yml
- Gemfile
- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/active_record/dirty.rb
- spec/generators/rails/mobility/install_generator_spec.rb
- spec/generators/rails/mobility/translations_generator_spec.rb
- spec/support/helpers.rb
The generator specs currently use the `RAILS_VERSION` env variable, but we use the string `"latest"` to run specs against the latest versions of AR and Sequel, so those specs are currently failing even though they should actually pass. This fixes that issue.
> Fix generator spec issues with latest AR version

- lib/mobility/plugins/active_record/dirty.rb
These AM::Dirty methods are no longer overridden in AR::Dirty 5.2, so we don't need the overrides anymore.
> Disable AR::Dirty method overrides for AR >= 5.2

- .travis.yml
- Gemfile
- Rakefile
- lib/mobility/backends/sequel/table/query_methods.rb
- spec/mobility/backends/sequel/hstore_spec.rb
- spec/mobility/backends/sequel/jsonb_spec.rb
> Fix Sequel 5 issues

- lib/mobility/backends/active_record/key_value.rb
- spec/support/shared_examples/dup_examples.rb
> Fix duping for AR KeyValue backend

- lib/mobility/backends/active_record/hstore/query_methods.rb
- lib/mobility/backends/active_record/jsonb/query_methods.rb
I noticed that using `inject` without an argument helps clean up these classes a bit.
> Refactor AR pg query methods

- lib/mobility/active_record.rb
- lib/mobility/plugins/active_record/attribute_methods.rb
- spec/integration/active_record_compatibility_spec.rb
- spec/mobility/active_record_spec.rb
- spec/mobility/plugins/active_record/attribute_methods_spec.rb
> Move translated_attribute_names to Mobility::ActiveRecord

- spec/support/shared_examples/querying_examples.rb
I noticed that the jsonb/hstore querying code was not being entirely tested, specifically the code path where you call `or` with a hash including both translated and untranslated attributes.
The line in question is here: https://github.com/shioyama/mobility/blob/57b1045acd1a7a9941f5481d250af8864359b316/lib/mobility/backends/sequel/postgres_query_methods.rb#L29
Without this change, this ternary can be replaced with simply `super(i18n_query, &block)` and specs will pass.
The specs now fail without the full code, and correctly test the different code paths.
> Improve Sequel querying examples for 'or'

- README.md
Seems the fallbacks had moved to `Mobility::Plugins`. Updated the link
to correct rubydoc page url.
> Fix readme link to fallbacks rubydoc

- lib/mobility/backends/active_record/table/query_methods.rb
This is simpler and avoids mutating the relation.
> Check joins_values to determine if query has been joined already

- lib/mobility/backends/active_record/key_value.rb
This is cleaner than checking if a private method has been defined.
> Use module to avoid duplicate method definitions

- .travis.yml
I forgot there was a `dist: precise` in the .travis.yml...
> Use trusty on travis

- lib/mobility/plugins/default.rb
- spec/mobility/plugins/default_spec.rb
Currently, you can use the `default` plugin with a `Proc`, with the proc being passed the model, attribute name, locale and options as keyword arguments. This ends up being quite clumsy to handle in practice.
This PR changes things so that instead, the context in the proc becomes the model, and the proc is passed up to three arguments: attribute, locale, options, but depending on the proc's arity it will only be passed enough arguments so that it can handle them.
This way, you can e.g. do this:
```
class Post < ApplicationRecord
extend Mobility
translates :title, default: lambda { |attr| self[attr] }
end
```
...and this will default to reading the `title` column if the `title` attribute is not defined on the backend (`self[attr]` is equivalent to `read_attribute(attr)`).
> Make default plugin handle Procs more gracefully

- lib/mobility/active_record.rb
Small change: we should avoid `define_method` whenever possible, for performance reasons. Also, I'd like to start naming modules, even if they are just a subclass of `Module`, to make them easier to see in the chain of ancestors.
> Use module_eval to define query scope, and name module

- lib/mobility/attributes.rb
In general `define_method` is faster to define, but slower on dispatch. For these accessor methods, I think it's safe to assume we want to prioritize performance on dispatch.
> Define accessors with eval

- Gemfile
- spec/active_record/models.rb
- spec/active_record/schema.rb
- spec/integration/active_record_compatibility_spec.rb
- spec/mobility/backends/sequel_spec.rb
- spec/mobility/plugins/sequel/dirty_spec.rb
- spec/sequel/models.rb
- spec/sequel/schema.rb
- spec/support/matchers/include_hash.rb
- spec/support/shared_examples/querying_examples.rb
Currently, the Sequel model tables are missing timestamps, and both AR and Sequel have some unnecessary tables, etc., result being that tests for each ORM cannot be run on the same table (so I need to drop and rebuild the table every time I switch from one to the other). This is kind of a pain.
These changes line up both ORMs so that tables are the same for both.
> Refactor test schemas so AR and Sequel can run on same db

- lib/mobility/backends/active_record/container.rb
- lib/mobility/backends/active_record/container/query_methods.rb
- lib/mobility/backends/active_record/hstore/query_methods.rb
- lib/mobility/backends/active_record/jsonb/query_methods.rb
- lib/mobility/backends/active_record/pg_query_methods.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/backends/container.rb
- lib/mobility/backends/sequel/container.rb
- lib/mobility/backends/sequel/container/query_methods.rb
- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/sequel/pg_hash.rb
- lib/mobility/backends/sequel/table.rb
- lib/mobility/sequel/column_changes.rb
- lib/mobility/sequel/hash_initializer.rb
- spec/active_record/schema.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/mobility/backends/sequel/container_spec.rb
- spec/sequel/schema.rb
This is the first new backend to be added to Mobility since all the original ones were introduced in v0.1.x. I was inspired to add it looking at the Elixir hex package named [Trans](https://hex.pm/packages/trans), which stores all translations for a model in a single depth-2 jsonb column (`translations`). I've seen this also discussed [elsewhere](https://github.com/denkGroot/Spina/issues/266#issuecomment-312824064), and thought it would be interesting to implement.
This implementation piggy-backs on parts of the existing Jsonb backend, but in other parts is entirely independent. Specs seem to be passing.
Regarding naming, I'm using the term "container" since this is what Trans uses. In the code I've called the backend "JsonbContainer", but this is quite a mouthful so I'm thinking of just …
> Add new jsonb container backend

- README.md
- lib/mobility.rb
- lib/mobility/configuration.rb
- lib/mobility/plugins/fallbacks.rb
- spec/mobility/configuration_spec.rb
- spec/mobility_spec.rb
See #81 and [this SO question](https://stackoverflow.com/questions/46547719/how-to-set-default-fallbacks-for-mobility).
> Rename default_fallbacks configuration to new_fallbacks / fallbacks_generator=

- lib/mobility/backends/active_record/container/query_methods.rb
- lib/mobility/backends/active_record/hstore/query_methods.rb
- lib/mobility/backends/active_record/jsonb/query_methods.rb
- lib/mobility/backends/active_record/pg_query_methods.rb
- lib/mobility/backends/sequel/container/query_methods.rb
- lib/mobility/backends/sequel/hstore/query_methods.rb
- lib/mobility/backends/sequel/jsonb/query_methods.rb
- lib/mobility/backends/sequel/pg_query_methods.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/mobility/backends/active_record/jsonb_spec.rb
- spec/mobility/backends/sequel/container_spec.rb
- spec/mobility/backends/sequel/jsonb_spec.rb
Currently, queries on jsonb columns in the `Jsonb` and `Container` backends are performed using the "contains" operator (`@>`). This works fine for string/integer/boolean values, but for hash valued-translations it returns a match even if the hash contains other keys/values (i.e. it does not perform an exact match).
Instead of using "contains" (`@>`), we can also use the normal element operator (`->`), so for a query `Post.i18n.where(title: { "a" => "b" })`, instead of this:
```sql
SELECT "posts".* FROM "posts" WHERE ("posts"."title" @> '{"en":{"a":"b"}}')
```
we instead get this:
```sql
SELECT "posts".* FROM "posts" WHERE (("posts"."title" -> 'en') = '{"a":"b"}')
```
The first SQL will match a post with a title value `'{"a":"b","c":"d"}'`, but the second will not.
Although this is an …
> Use element operator instead of contains for jsonb querying

- lib/mobility/backends/active_record/column/query_methods.rb
- lib/mobility/backends/active_record/key_value/query_methods.rb
- lib/mobility/backends/active_record/query_methods.rb
- lib/mobility/backends/active_record/table/query_methods.rb
- lib/mobility/backends/sequel/column/query_methods.rb
- lib/mobility/backends/sequel/container/query_methods.rb
- lib/mobility/backends/sequel/hstore/query_methods.rb
- lib/mobility/backends/sequel/jsonb/query_methods.rb
- lib/mobility/backends/sequel/key_value/query_methods.rb
- lib/mobility/backends/sequel/pg_query_methods.rb
- lib/mobility/backends/sequel/query_methods.rb
- lib/mobility/backends/sequel/table/query_methods.rb
In #159, I changed how the jsonb and container backends query on translated attributes, but I noticed that this wasn't applying to some `first_by_<x>`-type queries in Sequel. The reason is that some code had not been updated to the new format, but I realized it's much easier to just refactor all this `first_by_<x>` (Sequel) + `find_by_<x>` (AR) method code to define these methods *once*, basically as an alias independent of the backend query details.
This improves consistency and also chops off about 50 lines of code :smile:
> Refactor find_by for translated attributes

- lib/mobility/plugins/active_model/dirty.rb
We should avoid hard-coding options from plugins in other plugins. The
locale: true option specifies to all plugins that they should only
return a value for the locale specified, nothing else.
> Use locale:true instead of fallback: false in dirty plugin

- mobility.gemspec
i18n version [1.0.0](https://rubygems.org/gems/i18n/versions/1.0.0) was released a few days ago, but Mobility has a dependency on i18n < 1.0. Updating the dependency to include 1.0 to see if specs pass.
> Upgrade i18n dependency and test against 1.0.0

- .travis.yml
- lib/mobility.rb
- lib/mobility/configuration.rb
- lib/mobility/fallbacks.rb
- spec/mobility/plugins/fallbacks_spec.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
> Fall through to I18n.fallbacks when defined

- lib/mobility/backends/active_record/json.rb
- lib/mobility/backends/active_record/json/query_methods.rb
- lib/mobility/backends/json.rb
- lib/mobility/backends/sequel/json.rb
- lib/mobility/backends/sequel/json/query_methods.rb
- spec/active_record/schema.rb
- spec/mobility/backends/active_record/json_spec.rb
- spec/mobility/backends/sequel/json_spec.rb
- spec/sequel/schema.rb
Currently Mobility only  supports the `jsonb` column type. This PR adds support for the `json` type.
> Support postgres json type

- lib/mobility/backends/active_record/container.rb
- lib/mobility/backends/active_record/container/json_query_methods.rb
- lib/mobility/backends/active_record/container/jsonb_query_methods.rb
- lib/mobility/backends/active_record/json/query_methods.rb
- lib/mobility/backends/active_record/pg_query_methods.rb
- lib/mobility/backends/sequel/container.rb
- lib/mobility/backends/sequel/container/json_query_methods.rb
- lib/mobility/backends/sequel/container/jsonb_query_methods.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/mobility/backends/sequel/container_spec.rb
Currently, the Container backend requires a `jsonb` column. With this change, we check the column type and correctly handle translations on a `json` column in the same way, and raise if the column type is neither `json` nor `jsonb`.
> Add json column support to container backend

- lib/mobility/backends/active_record/key_value/query_methods.rb
- lib/mobility/backends/active_record/table/query_methods.rb
Why use ActiveSupport when you don't have to?
> Array.wrap -> Kernel::Array

- Gemfile
- lib/mobility/plugins/active_record/dirty.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/cache_key_examples.rb
Specs fail on 5.2.0.rc1, but some changes in that version have been [reverted](https://github.com/rails/rails/commit/5fcbdcfb574c731841be12764c50d9587b58345f), so I've updated the Gemfile to look at master and I'll try to fix the remaining issues here.
Against master at this time, six specs (related to dirty attribute tracking) are currently failing.
> Update for AR 5.2.0.rc2

- lib/mobility/active_record/uniqueness_validator.rb
- lib/mobility/backends/active_record/column.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/serialized.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/plugins/fallbacks.rb
- missing `extend Mobility` in many examples
- no mention that `validates` must be called after `extend Mobility` for uniqueness validator to work
> Add missing documentation

- lib/rails/generators/mobility/templates/table_translations.rb
- spec/generators/rails/mobility/translations_generator_spec.rb
Since we already generate a unique index on the `[foreign_key, :locale]` pair, the index on `foreign_key` alone is unnecessary.
@pwim Curious about this, what indices do you have on your translation tables? See the change here. I don't think we need `:post_id` if we already have `[:post_id, :locale]`, and if we don't need an index better not to generate it.
> Remove table backend index on foreign key alone

- lib/mobility/backends/active_record/table.rb
This may also be useful for KeyValue backend, but for now just adding it for the Table backend. Now you can call:
```ruby
post.translations.in(:en)
```
... and you get all translations in that locale. Currently, you'd need to do this:
```ruby
post.translations.find { |t| t.locale == "en" }
```
which is kind of annoying, especially if you do it frequently. I also refactored the backend to use this extension method.
> Add extension to find translations in a locale for Table backend

- lib/rails/generators/mobility/templates/create_string_translations.rb
- lib/rails/generators/mobility/templates/create_text_translations.rb
- spec/active_record/schema.rb
- spec/generators/rails/mobility/translations_generator_spec.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/sequel/schema.rb
I noticed there were warnings in the Rails 4.2 specs because `null: false` is not specified on `timestamps` in migrations. While fixing that, I've also enforced this constraint on KeyValue migrations for all columns other than `value`, which I think is a better default.
This will be released in 0.6.0 (should be the last release before 1.0).
> Enforce null: false constraint on columns consistently

- lib/mobility/backends/active_record/table/query_methods.rb
- spec/mobility/backends/active_record/table_spec.rb
This is a bug with the table backend:
```ruby
Post.i18n.joins(:translations).where(title: "foo")
#=> NoMethodError: undefined method `left' for :translations:Symbol#=> NoMethodError: undefined method `left' for :translations:Symbol
```
The `joins` here is redundant, but the exception is unexpected. We need to filter out non-arel nodes when checking to see if we have already joined translations.
> Ignore non-arel nodes in joins_values

- lib/mobility/backends/active_record/container/json_query_methods.rb
- lib/mobility/backends/active_record/container/jsonb_query_methods.rb
- lib/mobility/backends/active_record/hstore/query_methods.rb
- lib/mobility/backends/active_record/json/query_methods.rb
- lib/mobility/backends/active_record/jsonb/query_methods.rb
- lib/mobility/backends/active_record/pg_query_methods.rb
- lib/mobility/backends/sequel/container/json_query_methods.rb
- lib/mobility/backends/sequel/container/jsonb_query_methods.rb
- lib/mobility/backends/sequel/hstore/query_methods.rb
- lib/mobility/backends/sequel/json/query_methods.rb
- lib/mobility/backends/sequel/jsonb/query_methods.rb
- lib/mobility/backends/sequel/pg_query_methods.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/mobility/backends/active_record/jsonb_spec.rb
- spec/mobility/backends/sequel/container_spec.rb
- spec/mobility/backends/sequel/jsonb_spec.rb
- spec/support/shared_examples/querying_examples.rb
Currently a query like `Post.i18n.where(title: ["foo", "bar"])` with a PostgreSQL backend will use `OR` on each match in the array, but really we should be using `IN` for this. This PR changes the logic of pg query method classes to make this possible.
I'll update Sequel as well once AR specs are green.
> Use IN when querying on array values with PG backends

- lib/mobility/backends/active_record/table/query_methods.rb
- spec/mobility/backends/active_record/table_spec.rb
Currently with the Table backend, depending on what you query on, Mobility will use an `INNER` or `OUTER` join depending on the query values. This works well unless you split your query across multiple `where`s, like this:
```ruby
Post.i18n.where(title: nil).where(content: "foo")
```
If both `title` and `content` are translated on a translation table, in this case we should use an `INNER` join since we will only match posts which have a translation with content "foo". However, currently Mobility sees `title: nil` and uses an `OUTER` join.
This PR fixes this so that this query will correctly use an `INNER` join in this case as well.
> Improve use of INNER/OUTER joins with AR Table backend

- lib/mobility/attributes.rb
- spec/mobility/attributes_spec.rb
This makes it much easier to understand what's going on when inspecting a module's ancestors.
> Add inspect method to Attributes

- lib/mobility/active_model/backend_resetter.rb
- lib/mobility/active_record/backend_resetter.rb
- lib/mobility/sequel/backend_resetter.rb
These `Module.new`s are completely unnecessary since we can define the method directly on the module itself.
> Remove unneeded anonymous module in backend resetters

- lib/mobility/attributes.rb
- lib/mobility/plugins/default.rb
- spec/mobility/plugins/default_spec.rb
The inline comments say these will be removed in v1.0, but the deprecation messages just say the next version. Let's just get rid of them in 0.6.
> Remove some deprecated methods

- lib/mobility/backends/active_record/pg_hash.rb
- lib/mobility/backends/active_record/pg_query_methods.rb
- lib/mobility/backends/active_record/serialized.rb
- lib/mobility/backends/hash_valued.rb
- lib/mobility/backends/sequel/pg_hash.rb
- lib/mobility/backends/sequel/pg_query_methods.rb
- lib/mobility/backends/sequel/serialized.rb
> Add column_affix when configuring options

- lib/mobility/plugins/locale_accessors.rb
For methods which will be called more often than they will be defined, it's generally better to use `module_eval` which is faster on dispatch (but slower to define).
> Use module_eval to define locale accessors

- lib/mobility/configuration.rb
- lib/mobility/plugins.rb
- lib/mobility/plugins/default.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/presence.rb
- spec/mobility/plugins/default_spec.rb
Currently, the Default plugin is included in every backend. We can avoid this using the trick of a constant pointing to `Object.new` to signify an unset option key.
Also, I converted the plugin into a normal module rather than a module builder. Doesn't seem to affect performance but all else equal, normal modules are preferred.
> Do not include Default plugin by default

- lib/mobility/attributes.rb
- lib/mobility/backends/sequel/query_methods.rb
Extracted from #229. I don't know why I ever thought it was ok to bang-assign attributes but it's not a good idea...
> Freeze attributes array

- lib/mobility/arel.rb
- lib/mobility/arel/nodes.rb
- lib/mobility/arel/visitor.rb
- lib/mobility/backends/active_record.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/plugins/active_record/query.rb
- spec/active_record/schema.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/plugins/active_record/query_spec.rb
- spec/sequel/schema.rb
- spec/support/shared_examples/querying_examples.rb
(This is a follow-up to #216.)
This PR implements **full support** for querying using Arel translation nodes across all backends. It's taken a lot of thought to get here, but I think this will be a very important change for anyone using Mobility with querying, particularly complex querying.
In previous versions of Mobility, you could call `where` and `not` on a scoped relation on a translated model, and Mobility would convert translated attributes into their corresponding backend-specific nodes. However, this meant that you were limited to equality-type predicates, since that's all that `where` supports.
So I thought: what if you could just get an Arel node for a backend attribute? Then you could build your own queries with the node, e.g. `title.eq("foo")` but also `title.matches("foo")`, …
> Use backend visitors to fully support Arel queries

- .travis.yml
- lib/mobility/arel.rb
- lib/mobility/arel/visitor.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/table.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/support/shared_examples/querying_examples.rb
This is currently supported (although not tested) by all backends except KeyValue and Table. Should be straightforward to support universally.
The format looks like this:
```ruby
Post.i18n(locale: :en) do |en|
Post.i18n(locale: :ja) do |ja|
en.title.eq("Title").and(ja.title.eq("タイトル"))
end
end
```
This queries for a post with an English title `Title` and a Japanese title `タイトル`, but obviously you could build much more complex logic.
Here is the resulting SQL for a Jsonb backend:
```sql
SELECT "posts".* FROM "posts"
WHERE ("posts"."title" -> 'en') = '"foo"' AND ("posts"."title" -> 'ja') = '"bar"'
```
The problem with KeyValue and Table backends is that their respective joins do not alias the table name with an alias that includes the locale.
> Support querying on multiple locales at once

- lib/mobility/plugins/active_record/query.rb
- spec/support/shared_examples/querying_examples.rb
Replaces #210, much simpler now.
> Allow passing locale to query methods

- lib/mobility/arel/nodes/pg_ops.rb
- lib/mobility/backends/active_record/container.rb
- spec/support/shared_examples/querying_examples.rb
Previously it was not possible to create equality predicates between jsonb nodes. This fixes the issue, so you can do:
```ruby
Post.i18n { title.eq(content) }
```
... and Mobility will return all posts whose `title` and `content` are the same, for Jsonb (and Container) backends (already worked for other backends). I think this is the last issue to fix before releasing 0.7.0 :tada:
> Support equality predicates between jsonb nodes

- lib/mobility/active_record/uniqueness_validator.rb
- spec/support/shared_examples/validation_examples.rb
This reverts #237, which seemed to cause issues in SpinaCMS. Will investigate further later.
> Revert unscoping in uniqueness validator

- lib/mobility/active_record/uniqueness_validator.rb
- spec/support/shared_examples/validation_examples.rb
I'll merge this once specs pass, but we can release in the next minor instead of 0.7.x.
> Correctly unscope in uniqueness validator and fix specs

- lib/mobility.rb
- spec/mobility_spec.rb
Fixes issue mentioned [here](https://github.com/shioyama/mobility/issues/243#issuecomment-395302188).
> Normalize locales with multiple dashes and raise exception if locale accessor cannot be defined

- lib/mobility.rb
- lib/mobility/backends/active_record/column.rb
- lib/mobility/backends/column.rb
- lib/mobility/configuration.rb
- lib/mobility/plugins/locale_accessors.rb
- lib/rails/generators/mobility/templates/column_translations.rb
- lib/rails/generators/mobility/templates/initializer.rb
- lib/rails/generators/mobility/translations_generator.rb
- spec/mobility/plugins/locale_accessors_spec.rb
- spec/mobility_spec.rb
For background, see: https://github.com/shioyama/mobility/issues/243#issuecomment-395302188
I don't like having Rails-specific code sprinkled around, but this seems fairly minimal and probably will avoid weird issues in Rails applications.
> Prefer Rails available_locales if loaded

- lib/mobility/attributes.rb
- spec/mobility/attributes_spec.rb
This is an edge case, but I noticed in a spec that the new way attributes are generated (from modules in ancestors) does not call `uniq` on the resulting array. This means if you call `translates` more than once with the same attribute name, you'll get duplicates in the array.
This shouldn't happen normally but I think it should be handled in a sensible way, which is to just call `uniq` on the array.
> Only return unique names from mobility_attributes method

- lib/mobility/attributes.rb
And use `grep` to fetch mobility modules from ancestors.
> Update inline docs for Mobility::Attributes

- mobility.gemspec
This was added by bundler when originally creating the gem, but we don't need it.
> Remove bundler development dependency

- lib/mobility/backends/active_record.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/table.rb
Whenever possible, we should always default to `Mobility.locale`.
> Default locale to Mobility.locale in apply_scope

- lib/mobility/plugins/active_record/query.rb
This kind of subtle, but basically if the query map here is the identity function, it means we did not match *any* keys to module keys, so there is nothing to do here. Checking if it is nil is meaningless since inject in this case will always return something.
> Yield to block (super) if query map is the identity function

- spec/support/shared_examples/querying_examples.rb
We now support querying with a locale option in Sequel, like this:
```ruby
Post.i18n.where(title: "foo", locale: :ja).select_all("posts").all
#=> SELECT * FROM posts ...
```
so we should have tests to ensure this is working. Note that like with ActiveRecord, the `locale` value here cannot be an array (but this will be supported in the future).
> Add specs to Sequel querying examples for querying on locale

- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/sequel/table.rb
- lib/mobility/plugins/sequel/query.rb
- spec/sequel/schema.rb
- spec/support/shared_examples/querying_examples.rb
This brings Sequel support almost up to the same level as ActiveRecord (except missing support for `order` in the Query plugin, which I may try to add before releasing 0.8.0).
> Support block query format with Sequel

- CHANGELOG.md
We're still running on a bit outdated Ruby version, so the required ruby version change in https://github.com/shioyama/mobility/pull/242 was an unfortunate surprise to us given that it was not mentioned in the changelog.
So here's an update to the changelog so others won't get bitten by the same change :smile:
Looks like we should upgrade Ruby quite soon 😅
> Mention required ruby version change in 0.8.0 changelog

- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/table.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
Currently we default to an INNER join for the Table and KeyValue backends, although this never has any impact when using `where` since we always have equality predicates which don't fall through to the default. But for `order`, we currently use INNER join, which means that:
```ruby
Post.i18n.order(:title)
```
will only return posts that have a non-NULL `title` column. This seems counter-intuitive to me, so I'm changing the behaviour to use an OUTER join here so that all posts will be returned, even if they do not have a translation (in this case `title` will be ordered as if it was `nil`).
I also found a small bug where `&&` was returning `false` instead of `nil`, fixed here.
> Default to OUTER JOIN for Table, KeyValue backends

- .codeclimate.yml
- .gitignore
- lib/mobility/plugins/active_record/query.rb
- spec/support/shared_examples/querying_examples.rb
Ref: #275
@wenderjean This is an implementation of just `pluck`. As it turns out `select` is a little more tricky to do, so I'll leave that to do separately.
`group` should I think also be simple.
> Add support for pluck on translated attributes

- lib/mobility/arel.rb
- lib/mobility/arel/nodes/pg_ops.rb
- lib/mobility/backends/active_record/column.rb
- lib/mobility/plugins/active_record/query.rb
- spec/support/shared_examples/querying_examples.rb
> Implement select/group in AR query plugin

- lib/mobility/arel/nodes/pg_ops.rb
- lib/mobility/attributes.rb
- lib/mobility/backend.rb
- lib/mobility/backends/active_record/container.rb
- lib/mobility/backends/active_record/pg_hash.rb
- lib/mobility/backends/hash.rb
- lib/mobility/backends/sequel/jsonb.rb
- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/serialized.rb
- lib/mobility/configuration.rb
- lib/mobility/plugins/active_record/query.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/sequel/query.rb
- spec/mobility/backends/hash_spec.rb
I had a need for a non-persisted translated model and realized there was no backend for this use case, although many of Mobility's plugins (e.g. fallbacks) work with unpersisted models. So I created a minimal one called the Hash backend, which as its name implies just uses a hash for translations (similar to JSON backends).
> Add virtual (unpersisted) Hash backend

- lib/mobility/attributes.rb
- lib/mobility/configuration.rb
- lib/mobility/plugins.rb
- lib/mobility/plugins/default.rb
This is so much simpler than how it is currently done.
Have to give credit where credit is due:
http://www.virtuouscode.com/2011/05/30/null-objects-and-falsiness/
> If we’re trying to coerce a homemade object into acting falsey, we may be chasing a vain ideal. With a little thought, it is almost always possible to transform code from typecasing conditionals to duck-typed polymorphic method calls. All we have to do is remember to represent the special cases as objects in their own right, whether that be a Null Object or something else.
This made me realize we shouldn't be checking for special objects in the plugins, but instead simply checking if the key is present before even applying the plugins, which is much cleaner.
> Only apply plugins if options key is set

- lib/mobility.rb
This is a subtle edge-case, but I18n.locale_available? will not actually check that the current locale is included in *rails-defined* locales.  This may cause problems, for example, if you set available locales in Rails and then try to use Mobility in an initializer, since Rails may not yet have set I18n.available_locales.
Anybody else notice this issue?
> Check rails i18n locales when enforcing available locales

- lib/rails/generators/mobility/templates/create_string_translations.rb
- lib/rails/generators/mobility/templates/create_text_translations.rb
- spec/generators/rails/mobility/install_generator_spec.rb
> Use references to define polymorphic associations in generator migrations

- lib/mobility/backend.rb
- spec/mobility/plugins/default_spec.rb
- spec/mobility/plugins/fallbacks_spec.rb
This isn't actually used anywhere except in specs.
> Remove block handling from with_options

- lib/mobility/backends/active_record/table.rb
- spec/mobility/backends/active_record/table_spec.rb
Destroying records during `each` messes up the loop internal pointer, so when there is more than one empty translation some of them are not destroyed.
> Fix destroying empty translations in AR table backend

- lib/mobility/plugins/active_record/dirty.rb
- spec/mobility/backends/active_record/hstore_spec.rb
- spec/mobility/backends/active_record/json_spec.rb
- spec/mobility/backends/active_record/jsonb_spec.rb
This only matters for ActiveRecord 5.1 with Dirty enabled.
Fixes #308.
> Handle case when attribute name passed to `has_attribute` is not a string

- .travis.yml
- spec/sequel/schema.rb
Seems the schema should use `text: true` to specify text columns, rather than `size`.
> Fix breaking sequel specs

- lib/mobility.rb
Loading the Sequel inflection support will cause conflicts with the inflectors from Rails
See issue #325 for details
> Conditionally load the Sequel inflections

- .travis.yml
This PR updates the CI matrix by using the latest version of Ruby.
(2.4.7 had install problems today on `rvm` in Travis, so I left that as a next update.)
> CI: Use newer 2.5.6, 2.6.4

- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/active_record/dirty.rb
- spec/mobility/plugins/active_model/dirty_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
Resolving issues raised in #347, for master branch. For a summary see [here](https://github.com/shioyama/mobility/pull/347#issuecomment-544742401), and 011575d9859b086330197d50427773e79f29d94d.
> Fix issues with dirty plugin by dynamically defining dirty methods

- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/active_record/dirty.rb
- lib/mobility/plugins/dirty.rb
- lib/mobility/plugins/sequel/dirty.rb
- spec/mobility/plugins/active_model/dirty_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
- spec/mobility/plugins/dirty_spec.rb
Second attempt, following #347
> Fix Dirty plugin with Rails 6 (0-8-stable branch), take 2

- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/cache.rb
- spec/mobility/plugins/cache_spec.rb
`changes_applied` is private in some versions of Rails, and we should not be changing that. To avoid this from happening, we can create a dummy class including the AR dirty module, check its methods and see if either `changes_applied` or `clear_changes_information` are private, and if so change the method visibility accordingly.
Note: I will only be applying this to the `master` branch, where I noticed ae06d748626771a5114506c6a4ec85a9359dfba7 had changed the cache code. I won't be back-porting this to the 0-8 branch unless anybody had any issues, but I think in versions of Rails <= 5.1, the cache plugin makes `changes_applied` public when it is actually private in AR models. This probably is not a problem for anybody which I guess is why I haven't heard about it, but Mobility should …
> Avoid making private methods accidentally public

- lib/mobility/plugins/active_record/query.rb
- spec/support/shared_examples/querying_examples.rb
See:
- https://gist.github.com/dlcmh/9879954ec029162b6788640ef250e216
- https://github.com/shioyama/mobility/issues/358
> ArgumentError: Call `select' with at least one field

- lib/mobility/attributes.rb
- spec/mobility/attributes_spec.rb
There is a valid use case for using `Mobility::Attributes` with plugins, but without a backend, so we should not require a backend class.
> Do not raise exception for missing backend

- lib/mobility/plugins/active_model/dirty.rb
This isn't actually used anywhere.
> Do not delegate dirty_class from instance to class

- lib/mobility/plugins/fallthrough_accessors.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
Fixes #376 for `master` branch.
> Handle options keywords correctly in FallthroughAccessors plugin

- lib/mobility/plugins/fallthrough_accessors.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
Fixes #376 for 0-8-stable branch.
Related: #377
> Handle options keywords correctly in FalthroughAccessors plugin (0-8-stable branch)

- .github/workflows/ci.yml
- mobility.gemspec
- spec/mobility/attributes_spec.rb
- spec/mobility/plugins/cache_spec.rb
- spec/mobility/plugins/default_spec.rb
- spec/mobility/plugins/fallbacks_spec.rb
- spec/mobility/plugins/presence_spec.rb
> Deprecate Ruby 2.4, support Ruby 2.7

- lib/mobility/plugin.rb
- lib/mobility/plugins/dirty.rb
I'm in the process of breaking up Mobility into some finer-grained plugins (for readers/writers and backend itself), but doing that will require the concept of "dependencies" between plugins. Currently there is only one of these: dirty depends on fallthrough accessors. I'm adding a `depends_on` class method to define the dependency explicitly to make further changes down the line easier.
> Add depends_on for plugins to declare plugin dependencies

- lib/mobility.rb
- lib/mobility/plugins.rb
- lib/mobility/plugins/active_record/query.rb
- lib/mobility/plugins/attribute_methods.rb
- lib/mobility/plugins/cache.rb
- lib/mobility/plugins/default.rb
- lib/mobility/plugins/dirty.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/fallthrough_accessors.rb
- lib/mobility/plugins/locale_accessors.rb
- lib/mobility/plugins/presence.rb
- lib/mobility/plugins/query.rb
This is an idea borrowed from Shrine, Roda and other gems. Basically, we shouldn't be just assuming every plugin is in the Mobility::Plugins namespace, and that everything in this namespace is a plugin (some classes like Mobility::Plugins::ActiveModel, etc are actually not).
By explicitly declaring the mapping between keys and plugin modules, things are clearer, easier to test, and easier to extend (e.g. if you don't require a plugin from Mobility, you can use the same key for your own plugin module).
> Register plugins explicitly

- .github/workflows/ci.yml
It's really old now, no way we need to be testing against it anymore.
> Remove Sequel 4 from builds

- lib/mobility.rb
- lib/mobility/backends.rb
- lib/mobility/backends/column.rb
- lib/mobility/backends/container.rb
- lib/mobility/backends/hash.rb
- lib/mobility/backends/hstore.rb
- lib/mobility/backends/json.rb
- lib/mobility/backends/jsonb.rb
- lib/mobility/backends/key_value.rb
- lib/mobility/backends/null.rb
- lib/mobility/backends/serialized.rb
- lib/mobility/backends/table.rb
Declares backends the way we now declare plugins, making the relationship between the backend key and the backend class explicit and customizable.
Similar to #393 for plugins, but for backends.
> Register backends explicitly

- lib/mobility.rb
- lib/mobility/attributes.rb
- lib/mobility/configuration.rb
- lib/mobility/plugin.rb
- lib/mobility/plugins.rb
- lib/mobility/plugins/dirty.rb
- spec/mobility/plugin_spec.rb
- spec/support/helpers.rb
Currently, plugins are declared inside the body of a `Mobility::Attributes` instance. Dependencies declared with `depends_on` in the plugin are then included after the plugin itself.
This may not always be what we want, since multiple plugins may depend on each other. To correctly resolve dependencies, this requires wrapping plugin declarations in a block:
```ruby
class TranslatedAttributes < Mobility::Attributes
plugins do
foo
bar
end
end
```
In addition, plugins now declare dependencies with a required keyword argument, `include: :before` or `include: :after`, which specifies whether to include the dependency before or after the plugin itself. We then use `TSort` to sort dependencies such that the requirements on include order are met.
You can also add plugins one by one, like …
> Specify plugins in configure block, and declare before/after on dependencies

- lib/mobility/plugin.rb
- spec/mobility/plugin_spec.rb
This is a bit of a subtle point, but the code change here simply adds all previously included plugins to `visited` when it starts recursively building the dependency tree, thus skipping them and avoiding conflicts.
> Correctly handle previously-included mutual dependencies

- lib/mobility.rb
- lib/mobility/attributes.rb
- lib/mobility/configuration.rb
- lib/mobility/plugin.rb
- lib/mobility/plugins.rb
- lib/mobility/plugins/backend.rb
- spec/mobility/configuration_spec.rb
- spec/mobility/plugin_spec.rb
- spec/mobility/plugins/backend_spec.rb
Instead of having defaults in the configuration, define them alongside the plugins to which they apply:
```ruby
class TranslatedAttributes < Mobility::Attributes
plugins do
backend default: :key_value
fallbacks default: { en: [:en, :de], de: [:de, :en] }
locale_accessors default: [:en, :de]
end
end
```
This also works, provided the order of plugins doesn't conflict with dependency requirements:
```ruby
class TranslatedAttributes < Mobility::Attributes
plugin :backend, default: :key_value
plugin :fallbacks, default: { en: [:en, :de], de: [:de, :en] }
plugin :locale_accessors, default: [:en, :de]
end
```
> Define defaults with plugins

- lib/mobility/attributes.rb
- lib/mobility/pluggable.rb
- lib/mobility/plugin.rb
- spec/performance/attributes_spec.rb
Plugin inclusion and dependency resolving logic is pretty much entirely divorced now from any real concept of "attributes", so we can split the two cleanly and just have `Mobility::Attributes` subclass a minimal Module subclass, which I'll call `Mobility::Pluggable`.
With this separation, the remaining methods in `Mobility::Attributes` are non-essential and I think we can simply remove most of them since they are not widely used. The goal here is to have as close to zero assumptions baked into `Mobility::Attributes` as possible.
> Add Pluggable class

- lib/mobility/backend.rb
- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/plugins/backend.rb
- spec/mobility/backend_spec.rb
This method is barely used and code is easier to read if we just inline it.
> Remove Mobility::Backend.method_name

- CHANGELOG.md
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/backend_reader.rb
- spec/integration/active_record_compatibility_spec.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/backends/hash_spec.rb
- spec/mobility/backends/sequel/table_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
- spec/mobility/plugins/backend_spec.rb
- spec/mobility/plugins/cache_spec.rb
- spec/support/helpers.rb
- spec/support/shared_examples/dup_examples.rb
The Backend plugin does three basic things on the model class:
- defines getter method for each attribute (`title_backend` etc)
- defines `mobility_backends` (instance method) and
`mobility_backend_class` (class method) on model class
- sets up model with backend (calls `backend.setup_model` on model)
The defining of getter methods is not really required for any other plugins, since internally everything goes to `mobility_backends[:title]` instead of `title_backend` (former is faster, and for accessor methods in particular speed is important).
Also, the "X_backend" format being hard-coded has always kind of bothered me. So I thought, now that we have plugins, why not just split off that part into its own plugin? Call it `BackendReader.` And the format string can be the argument to that …
> Add BackendReader

- lib/mobility.rb
- lib/mobility/active_record/uniqueness_validator.rb
- lib/mobility/attributes.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/plugin.rb
- lib/mobility/plugins/active_record/query.rb
- lib/mobility/plugins/attributes.rb
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/sequel/query.rb
- spec/mobility/attributes_spec.rb
- spec/mobility/plugins/backend_spec.rb
- spec/performance/attributes_spec.rb
- spec/support/shared_examples/querying_examples.rb
That's it, now basically everything is a plugin.
Also, previously when calling methods like `mobility_attributes`, we'd `grep` all modules which are instances of `Mobility::Attributes`, grab their `names` and merge/flatten them. Same idea for backend classes. With this PR, we instead keep a running copy of what they are in an array, and add to it. Same for backend classes except we merge (since backend classes is a hash of keys->class).
Also: removed `BackendCache`, we don't need it.
> Extract Attributes into its own plugin

- .codeclimate.yml
- .rubocop.yml
- lib/mobility/plugin.rb
- lib/mobility/plugins.rb
- spec/mobility/plugin_spec.rb
There are situations where we want one plugin to depend on another one, without actually including it. e.g. I'm planning to restructure the Dirty and Query plugins so that you have an `active_record` plugin, an `active_record_dirty` plugin and a `dirty` plugin, where `active_record` depends on `active_record_dirty` (which has all the important code), and `active_record_dirty` depends on `dirty`, but in the latter case the dependency shouldn't automatically run unless `dirty` is explicitly included.
The change here adds the option to have `depends_on :foo, include: false`, which basically means you don't automatically include the dependency but just check in the initialize/included hooks to see if the dependency was included (separately), and only if so, run the code.
This way `dirty` …
> Support include: false in depends_on

- lib/mobility/pluggable.rb
- lib/mobility/plugin.rb
- lib/mobility/plugins/attribute_methods.rb
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/backend_reader.rb
- lib/mobility/plugins/cache.rb
- lib/mobility/plugins/dirty.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/fallthrough_accessors.rb
- lib/mobility/plugins/locale_accessors.rb
- lib/mobility/plugins/presence.rb
- lib/mobility/plugins/query.rb
- lib/mobility/plugins/reader.rb
- lib/mobility/plugins/writer.rb
- spec/mobility/plugins/backend_reader_spec.rb
- spec/mobility/plugins/cache_spec.rb
- spec/mobility/plugins/fallbacks_spec.rb
- spec/mobility/plugins/presence_spec.rb
- spec/mobility/plugins/reader_spec.rb
- spec/mobility/plugins/writer_spec.rb
Setting the default for a plugin via a keyword argument to initialize_hook and/or included_hook is problematic because then other plugins cannot see this default. It's better just to be explicit about it and declare the default, then we can set it on the defaults hash as soon as the plugin is included into a pluggable (module), so all plugins can see it from both hooks.
So now inside the hooks we have to be a bit more explicit and fetch `options[:foo]` instead of using a keyword parameter `foo: ...`, but after thinking this over carefully I think this is actually preferable.
> Set plugin default via DSL instead of keyword argument

- lib/mobility/configuration.rb
- spec/mobility/configuration_spec.rb
I'm not yet quite sure how we'll handle Configuration in v1.0, but basically it should delegate to the attributes class. With this change, you can now do this in 1.0:
```ruby
config.plugin :fallbacks, default: [:en, :ja]
end
```
This is just short for assigning the following class to `@attributes_class` on
`Mobility.configuration`:
```ruby
Class.new(Attributes) do
plugin :fallbacks, default: [:en, :ja]
end
```
> Allow passing options to attributes_class from configuration#plugin

- lib/mobility/configuration.rb
- lib/mobility/pluggable.rb
- spec/mobility/configuration_spec.rb
- spec/mobility/pluggable_spec.rb
Currently on `master` there is no obvious way to set defaults for backends, since defaults are tied to plugins. With this change you can now define them with a `default` class method on `Pluggable`.
With this change, we basically have patterns to replace `default_options` and `default_backend`. So here's how you configure options on 0.8.x:
```ruby
config.default_backend :key_value
config.default_options[:locale_accessors] = [:en, :ja]
config.default_options[:type] = :text
end
```
Notice here that `locale_accessors` is a plugin option, whereas `type` is an option for the `key_value` backend. The fact that the two look the same is a bad thing, I think, because they are handled differently.
In 1.0, this becomes:
```ruby
class TranslatedAttributes < …
```
> Add convenience method to define arbitrary defaults on Pluggable

- lib/mobility/plugin.rb
- lib/mobility/plugins/active_model.rb
- lib/mobility/plugins/active_model/cache.rb
- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/active_record.rb
- lib/mobility/plugins/active_record/backend.rb
- lib/mobility/plugins/active_record/cache.rb
- lib/mobility/plugins/active_record/dirty.rb
- lib/mobility/plugins/active_record/query.rb
- lib/mobility/plugins/active_record/uniqueness_validation.rb
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/backend_reader.rb
- lib/mobility/plugins/cache.rb
- lib/mobility/plugins/default.rb
- lib/mobility/plugins/dirty.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/presence.rb
- lib/mobility/plugins/query.rb
- lib/mobility/plugins/reader.rb
- lib/mobility/plugins/sequel.rb
- lib/mobility/plugins/sequel/backend.rb
- lib/mobility/plugins/sequel/cache.rb
- lib/mobility/plugins/sequel/dirty.rb
- lib/mobility/plugins/sequel/query.rb
- lib/mobility/plugins/writer.rb
- spec/mobility/plugin_spec.rb
The `include: false` usage is pretty cryptic with the method name "depends_on". Using the name "requires" makes the meaning clearer:
```ruby
module Mobility
module Foo
extend Plugin
requires :bar, include: false
end
end
```
So the `Foo` plugin *requires* `Bar`, but does not include it. If you want to use `Foo`, you need to also have the `Bar` plugin explicitly enabled (either included from another plugin, or included explicitly in the list of configuraiton plugins).
> Rename depends_on to requires

- CHANGELOG.md
- lib/mobility.rb
- lib/mobility/configuration.rb
- lib/mobility/plugins/dirty.rb
- lib/mobility/plugins/fallthrough_accessors.rb
- lib/mobility/plugins/locale_accessors.rb
- spec/mobility/configuration_spec.rb
- spec/mobility/plugins/dirty_spec.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
- spec/mobility/plugins/locale_accessors_spec.rb
- spec/support/matchers/have_plugin.rb
With the new plugin setup in v1.0, you need to explicitly enable plugins, like this:
```ruby
config.plugin :locale_accessors
end
```
Currently, this will not actually get you locale_accessors since the default option is `nil`. This PR makes the default for both `locale_accessors` and `fallthrough_accessors` be `true`, which in the former case defaults to `I18n.available_locales`.
This PR also removes the `default_accessor_locales` configuration setting, since there should be no need for it. Global defaults can now be defined from plugin configuration.
> Default locale_accessors and fallthough_accessors to enabled

- lib/mobility/pluggable.rb
- lib/mobility/plugin.rb
- lib/rails/generators/mobility/templates/initializer.rb
- spec/generators/rails/mobility/install_generator_spec.rb
- spec/mobility/pluggable_spec.rb
- spec/mobility/plugin_spec.rb
- spec/mobility/plugins/backend_reader_spec.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
Currently, plugins are declared like this:
```ruby
config.plugins do
backend default: :key_value
active_record
fallbacks default: [:en, :ja]
end
end
```
I find this sounds a bit funny and the syntax ends up being cumberesome. How about we just pass the argument directly to the method, like this?
```ruby
config.plugins do
backend :key_value
active_record
fallbacks [:en, :ja]
end
end
```
I find this feels more natural. It also gives a nice lead-in to defining backend options directly on the options to the backend plugin, like this:
```ruby
config.plugins do
backend :key_value, type: :string, ...
end
end
```
But this would require a bit more work, so I'll leave that to a separate PR.
> Pass argument to plugin rather than default: kwarg

- CHANGELOG.md
- lib/mobility/backend.rb
- lib/mobility/backends/active_record/container.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/backends/sequel/container.rb
- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/sequel/table.rb
- lib/mobility/plugins/backend.rb
- spec/mobility/backend_spec.rb
- spec/mobility/backends/active_record/column_spec.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/backends/sequel/key_value_spec.rb
- spec/mobility/backends/sequel/table_spec.rb
- spec/mobility/plugins/backend_spec.rb
- spec/support/shared_examples/backend_examples.rb
Merging the class into the options isn't really a very good idea, since it clutters the hash and makes it less clear what comes from where. Let's just pass it as a separate argument.
> Pass class explicitly to with_options and configure

- lib/mobility/plugin.rb
This will make it easier to customize argument-handling behaviour on the plugin itself.
> Eagerly load plugins as soon as they are declared in DSL

- lib/mobility/pluggable.rb
- lib/mobility/plugin.rb
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/dirty.rb
- spec/mobility/configuration_spec.rb
- spec/mobility/pluggable_spec.rb
- spec/mobility/plugin_spec.rb
- spec/mobility/plugins/backend_spec.rb
- spec/support/helpers.rb
Currently, you can define backend options like `association_name` like this:
```ruby
config.plugins do
backend :key_value
end
default :association_name, :foo
end
```
But I find this problematic for several reasons:
1. the `association_name` default is set on a `defaults` hash which is passed to all plugins, but it's not actually a plugin option but a backend option.
2. if you override the `backend` in options, you still get the `association_name` to the backend. But backend options are specific to the backend to which they are applied, and should not be passed to other backends
3. it's confusing when you read it because it's not clear what the `default` here is connected to.
What I _want_ is this:
```ruby
config.plugins do …
```
> Allow configuration to define backend options explicitly on backend

- README.md
- lib/rails/generators/mobility/templates/initializer.rb
It's going to be pretty confusing for anyone trying to use Mobility from the master branch with the currrent readme. Although some of this usage is not really "final", I think it's better to at least keep things roughly in sync.
I intend to rewrite a lot of this once the changes are done, since there is a single pattern for defining plugins and a lot of the readme sounds repetitive now. So consider this a "quick fix".
> Update readme to new v1 usage

- lib/mobility/plugin.rb
- spec/mobility/plugins/active_model/cache_spec.rb
- spec/mobility/plugins/active_model/dirty_spec.rb
- spec/mobility/plugins/active_record/cache_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
- spec/mobility/plugins/active_record/query_spec.rb
- spec/mobility/plugins/attribute_methods_spec.rb
- spec/mobility/plugins/cache_spec.rb
- spec/mobility/plugins/default_spec.rb
- spec/mobility/plugins/dirty_spec.rb
- spec/mobility/plugins/fallbacks_spec.rb
- spec/mobility/plugins/locale_accessors_spec.rb
- spec/mobility/plugins/presence_spec.rb
- spec/mobility/plugins/sequel/cache_spec.rb
- spec/mobility/plugins/sequel/dirty_spec.rb
- spec/mobility/plugins/writer_spec.rb
- spec/support/helpers.rb
This started as a simple spec cleanup but in the process I realized that the way the `plugins` block now works, it accepts optional kwargs which breaks setting a default hash in plugins that don't accept kwargs.
Mobility has to get this whole keyword arguments thing in order... but anyway the fix here is just to treat all arguments passed in the block as positional arguments, and let the backend plugin (which is the only plugin that accepts an options hash along with the backend name) handle the special case.
> Clean up spec helper and fix kwargs issue with plugins block

- spec/mobility/backends/sequel/container_spec.rb
- spec/mobility/backends/sequel/json_spec.rb
- spec/mobility/backends/sequel/jsonb_spec.rb
Tests were incorrectly checking if `Pg` is defined, but in fact the constant is `PG`.
Extracted from #437
> Postgres constant is PG, not Pg

- spec/support/helpers.rb
We shouldn't be depending on `String#constantize` being defined, even in a spec. `Object.const_get` should work just as well here.
> Use const_get instead of constantize to avoid dependency on inflections

- CHANGELOG.md
- lib/mobility/plugins/fallbacks.rb
- spec/mobility/plugins/fallbacks_spec.rb
Currently, if you have:
```ruby
config.plugins do
fallbacks
end
end
```
... the fallbakcs plugin will not actually apply unless you set `falbacks: true` or assign fallbacks to the hash key in models. This doesn't really make sense now that we're being more explicit about enabling plugins; it should be `true` by default once enabled. That's what this PR does.
> Default fallbacks plugin to `true`

- lib/mobility.rb
This is defined in the Attributes plugin, so doesn't need to be defined here.
> Remove Mobility::ClassMethods#mobility_attribute?

- lib/mobility/backend.rb
- lib/mobility/backends.rb
- lib/mobility/backends/key_value.rb
- lib/mobility/backends/table.rb
- lib/mobility/plugins.rb
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/cache.rb
- spec/mobility/backends/sequel/key_value_spec.rb
- spec/mobility/backends/sequel/table_spec.rb
- spec/mobility/plugins/backend_spec.rb
This method should not exist; it's only there for backends to hook into the cache plugin. Let's see if we can get rid of it.
> Remove Mobility::Backend#apply_plugin

- lib/mobility.rb
- lib/rails/generators/mobility/templates/initializer.rb
- spec/generators/rails/mobility/install_generator_spec.rb
- spec/mobility_spec.rb
This makes configuring Mobility slightly simpler.
So while we continue supporting this format:
```ruby
config.plugins do
end
end
```
we also suppport this:
```ruby
Mobility.configure do
plugins do
end
end
```
> Instance exec configure block if it takes no arguments

- CHANGELOG.md
- lib/mobility/backend.rb
- lib/mobility/backends/active_record/container.rb
- lib/mobility/backends/active_record/serialized.rb
- lib/mobility/backends/hash_valued.rb
- lib/mobility/backends/jsonb.rb
- lib/mobility/backends/key_value.rb
- lib/mobility/backends/sequel/container.rb
- lib/mobility/backends/sequel/serialized.rb
- lib/mobility/backends/table.rb
- lib/mobility/pluggable.rb
- lib/mobility/plugins/backend.rb
- spec/integration/active_record_compatibility_spec.rb
- spec/mobility/pluggable_spec.rb
- spec/mobility/plugins/backend_spec.rb
- spec/mobility/plugins/sequel/dirty_spec.rb
- spec/mobility/translations_spec.rb
- spec/mobility_spec.rb
I've noticed that with the changes to how plugins and backends are now configured, it's very easy to forget to define a plugin and pass the plugin option, without realizing that the option is just being ignored. This could have very problematic consequences, so we should raise in this case.
This should be simple, but in fact because of the way that backend options are mixed in, it's somewhat ugly to implement. This works but could perhaps be improved.
> Raise an exception if invalid options are passed to Translations initializer

- lib/mobility/plugins/fallthrough_accessors.rb
- lib/mobility/plugins/locale_accessors.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
- spec/mobility/plugins/locale_accessors_spec.rb
It should be possible to use locale/fallthrough accessors without a backend, since they simply function to map methods to other methods. The dependency is not meaningful, so I'm removing it.
> Don't make locale and fallthrough accessors dependent on backend

- lib/mobility/backend.rb
- lib/mobility/backends/active_record/container.rb
- lib/mobility/backends/container.rb
- lib/mobility/backends/sequel.rb
- lib/mobility/backends/sequel/container.rb
- lib/mobility/backends/sequel/json.rb
- lib/mobility/backends/table.rb
A few things:
- we should not register generic backends that have ORM-specific counterparts, like "Container", because they cannot actually be used on their own
- declare valid keys for backends in the generic backend module so these keys are the same for both ORM
- other minor stuff like using same variable naming, etc
> Streamline backends

- lib/mobility/arel.rb
- lib/mobility/backend.rb
- lib/mobility/backends/active_record/hstore.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/active_record/table.rb
- lib/mobility/backends/key_value.rb
- lib/mobility/backends/sequel/hstore.rb
- lib/mobility/backends/table.rb
- lib/mobility/plugins/active_model/dirty.rb
- lib/mobility/plugins/active_record/uniqueness_validation.rb
- lib/mobility/plugins/backend.rb
- lib/mobility/plugins/cache.rb
- lib/mobility/plugins/default.rb
- lib/mobility/plugins/fallbacks.rb
- lib/mobility/plugins/fallthrough_accessors.rb
- lib/mobility/plugins/presence.rb
- lib/mobility/plugins/reader.rb
- lib/mobility/plugins/sequel/dirty.rb
- lib/mobility/plugins/writer.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
- spec/mobility/plugins/attribute_methods_spec.rb
- spec/mobility/plugins/cache_spec.rb
- spec/mobility/plugins/fallbacks_spec.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
- spec/mobility/plugins/presence_spec.rb
- spec/mobility_spec.rb
- spec/performance/translations_spec.rb
- spec/support/shared_examples/accessor_examples.rb
- spec/support/shared_examples/locale_accessor_examples.rb
- spec/support/shared_examples/querying_examples.rb
Replaces #357. This is an attempt to get rid of deprecation warnings on 1.0. Original PR by @f1sherman, syncing it up with changes since that PR.
> Fix Ruby 2.7.0 Deprecation Warnings

- lib/mobility/plugins/attributes.rb
- lib/mobility/plugins/backend.rb
- spec/mobility/plugins/attributes_spec.rb
- spec/mobility/plugins/backend_spec.rb
Summary:
- make `mobility_attributes` public (see https://github.com/shioyama/mobility/pull/460#issuecomment-722445031)
- remove `register_mobility_attribute`, which was public but intended to be private (actually don't need it)
- add tests
Also, while I was add it I made a change to the backend plugin to remove `register_mobility_backend_class`, which we don't actually need either.
> Refactor attributes & backend plugins

- lib/rails/generators/mobility/templates/create_string_translations.rb
- lib/rails/generators/mobility/templates/create_text_translations.rb
- lib/rails/generators/mobility/templates/initializer.rb
E.g. Rubocop by default would complain as `Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.`
[ci skip]
> Remove empty lines in Rails generator templates

- CHANGELOG.md
- README.md
- lib/mobility/version.rb
- mobility.gemspec
I was going to wait until #467 was done, but we should just get this out already.
> Release 1.0.0

- lib/mobility/plugin.rb
I noticed that this line can actually load (`require`) a plugin that is not in fact needed, e.g. `active_record_dirty` depends on `dirty` being included but it should not actually have to load the dirty plugin to do this check.
The change here avoids that unnecessary file load.
> Define dependencies_satisfied? to avoid loading plugin

- lib/mobility/plugins/active_record/query.rb
- lib/mobility/plugins/active_record/uniqueness_validation.rb
- spec/mobility/plugins/active_record/query_spec.rb
There should be a way to build queries without using the query scope. This PR makes this more easily possible by making `Mobility::Plugins::ActiveRecord::Query::VirtualRow` public, and also adding a class method `Query.build_query` which can be used like this:
```ruby
Mobility::Plugins::ActiveRecord::Query.build_query(Post) do
title.eq('foo')
end
```
This is equivalent to:
```ruby
Post.i18n do
title.eq('foo')
end
```
The namespace is cumbersome but you can just name it something else in your application:
```ruby
I18nQueryScope = Mobility::Plugins::ActiveRecord::Query
```
then use:
```ruby
I18nQueryScope.build_query(Post) do
title.eq('foo')
end
```
> Make Mobility::Plugins::ActiveRecord::Query::VirtualRow public

- CHANGELOG.md
- lib/mobility.rb
- lib/mobility/plugins/active_record/query.rb
- lib/mobility/plugins/sequel/query.rb
- spec/mobility/plugins/active_record/query_spec.rb
- spec/mobility/plugins/sequel/query_spec.rb
I realized that querying using the block format can be made much more powerful if we allow passing the locale as an argument to the node method in the block, e.g.:
```ruby
Post.i18n do
title(:en).eq('foo').or(content(:ja).eq('bar'))
end
```
So the argument to `title` and `content` in the block is optional, but if passed will override the locale and apply it just to that node. With this change, it becomes really easy to do very complex queries across multiple languages in the same block.
WDYT folks?
> Allow setting locale per node in query block

- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/key_value.rb
- lib/mobility/backends/sequel/key_value.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/sequel/key_value_spec.rb
This option is not needed, since it can simply be inlined into the table_alias method.
> Remove internal table_alias_affix option

- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/sequel/key_value.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/sequel/key_value_spec.rb
Currently we include a module which adds an `after_destroy` hook to destroy both text and string translations after a model is destroyed, if it has any attributes using the KeyValue backend. This is a conservative move to ensure that string/text translations for a model are always cleaned up, even if a model may have changed code in the past from string to text (leaving behind orphan translations, for example).
However, this makes assumptions about the `translations_class`, which in general may use another class/table entirely.
~I think dealing with orphan translations should be the responsibility of the application developer, and the code itself should only define callbacks for _currently defined attributes_. Thus if a model only has string translations, then the `after_destroy` block …
> Call after_destroy in setup block to delete associated translations

- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/key_value.rb
- spec/mobility/backends/active_record/key_value_spec.rb
- spec/mobility/backends/sequel/key_value_spec.rb
In preparation for #385.
Also see #412.
> Add key, value and belongs_to options to key-value backend

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- lib/mobility/plugins/backend.rb
- lib/mobility/version.rb
- spec/mobility/plugins/backend_spec.rb
Fixes #492
This is not a super clean fix, but tests check that it's doing what one would expect.
cc @kevynlebouille
> Correctly override default backend options

- lib/mobility/plugins/backend.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/plugins/backend_spec.rb
Follow up to #499, which isn't working because `options[:cache]` does not include the default `true` option value.
Fixes #490.
> Merge options including defaults into backend options

- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/plugin.rb
Tests are failing now for some reason, although they were not before. Anyway we should be requiring `set` before using `Set`, so this is a good thing to do, but still... mysterious.
> Require set before referencing Set

- lib/mobility/plugins/active_record/query.rb
- spec/mobility/plugins/active_record/query_spec.rb
~This shouldn't be necessary from AR >= 7.0~ _Only one of the two checks is required in AR 7.0_
See: https://github.com/shioyama/mobility/issues/513
> Check whether class responds to mobility_attribute?

- .github/workflows/ci.yml
- lib/mobility.rb
- lib/mobility/plugins/fallthrough_accessors.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
If a `method_missing` is defined explicitly with kwargs in own code, for example like this:
```ruby
def method_missing(method_name, *args, **kwargs, &block)
...
end
```
*and* fallthrough accessors are used, it looks like `kwargs` are swallowed by mobility's definition of `method_missing`.
For now I only added a failing spec to illustrated what I think should happen.
The spec **passes on ruby 2.7** but **fails on ruby 3**.
I'm not sure what the solution is for now.
> Do not swallow keyword args on ruby 3 in fallthrough accessors

- lib/mobility/backend.rb
- spec/mobility/backend_spec.rb
- spec/mobility/backends/active_record/table_spec.rb
- spec/mobility/backends/sequel/table_spec.rb
- spec/mobility/plugins/backend_spec.rb
In practice, every backend class that is used in a model is a subclass of one of the base classes like `Mobility::Backends::ActiveRecord::KeyValue` etc. Configured backend classes have a model class (points to the class in which the backend is used) and set of options configuring it, whereas the base backend classes do not.
However, previously you could still call `options` or `model_class` on the base classes and you would get back a `nil`. This is confusing since those getter methods should never be called on the base backend classes.
In this commit I'm restructuring the code such that:
- getter methods raise on the base backend class
- methods which do not make sense on the base backend class are moved to a module which is included into backend subclasses.
I think this should avoid …
> Clearly distinguish backend classes from their configured subclasses

- lib/mobility/backend.rb
- lib/mobility/backends/active_record/key_value.rb
- lib/mobility/backends/sequel/container.rb
- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/sequel/pg_hash.rb
- lib/mobility/backends/sequel/table.rb
- spec/mobility/backend_spec.rb
Refactoring the `setup` block in backend classes can be difficult because the local context in the block is the model class, and we don't want to dump methods there.
This PR makes the `setup` block accept an optional third argument, the configured backend class, which can then be the receiver for method calls to extract common logic (or customizable logic) out of the `setup` block. An immediate use case for this is #525.
> Allow passing configured backend class as third argument to setup

- lib/mobility/backends/sequel/key_value.rb
- lib/mobility/backends/sequel/table.rb
- lib/mobility/plugins/sequel/query.rb
- spec/integration/sequel_compatibility_spec.rb
I noticed this wasn't working correctly while working on another PR. Once tests pass I'l ship this as 1.1.4.
> Fix Sequel querying on untranslated attributes in `i18n` block

- lib/mobility/backend.rb
- lib/mobility/plugins/backend.rb
- spec/mobility/backend_spec.rb
- spec/mobility/plugins/backend_spec.rb
Replaces #505
~I figured out how to avoid an md5 digest or other hack when naming configured backends. Basically, we don't name them based on their attributes but instead on the attribute names in the model that the backend class is created for. This is cleaner and means the backend class name is directly readable, so less unintuitive.~
~I've also assigned the name to a namespace under the backend class itself, rather than off of the root namespace. This way the name only has to incorporate the model name and attribute name(s).~
_Update: I simplified this by just avoiding dumping the backends at all (by defining `marshal_dump` and `marshal_load`), which gets around the problem entirely._
> Make models work with `Marshal.dump` (take two)

- lib/mobility/backends/active_record/container.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/support/matchers/not_change.rb
fixes dirty tracking and creating empty translation hashes on read
fixes #540
> clean up and refactor active record container backend

- lib/mobility/plugins/backend.rb
- spec/mobility/plugins/backend_spec.rb
Fixes mobility to work if subclassing a subclass of a mobility-enabled class, and looks up mobility_backend_classes later in execution (upon being called) to be more flexible.
fixes #566
> Fix issues with subclassing, such as when using ActiveRecord STI.

- lib/mobility/plugins/fallthrough_accessors.rb
- spec/mobility/plugins/fallthrough_accessors_spec.rb
Replaces: https://github.com/shioyama/mobility/pull/557
Fixes https://github.com/shioyama/mobility/issues/556
> Update fallthrough_accessor regex to allow for ISO 639-2 codes

- lib/rails/generators/mobility/templates/initializer.rb
This feature was implemented in 1.2 but I had to read the PR to understand how to use it. Thought I'd add it into the default initializer.
> Add column_fallback to Mobility initializer

- .github/workflows/ci.yml
- lib/mobility/plugins/backend.rb
This PR adds Ruby 3.1 and 3.2 to the test matrix of the CI pipeline so that we can rest assured that Mobility gem also works with recent major versions of Ruby.
> Test against Ruby 3.1 and 3.2

- .github/workflows/ci.yml
- Gemfile
- lib/mobility/backends/active_record/serialized.rb
- spec/active_record/schema.rb
- spec/generators/rails/mobility/install_generator_spec.rb
- spec/generators/rails/mobility/translations_generator_spec.rb
- spec/mobility/backend_spec.rb
- spec/mobility/backends/active_record/container_spec.rb
- spec/mobility/backends/active_record/json_spec.rb
- spec/mobility/backends/active_record/serialized_spec.rb
- spec/mobility/plugins/active_model/dirty_spec.rb
- spec/mobility/plugins/active_record/cache_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
- spec/mobility/plugins/sequel/query_spec.rb
- spec/mobility_spec.rb
- spec/support/shared_examples/serialization_examples.rb
Overdue cleanup.
Sequel
- Fix breaking test: The internal equality operator seems to have changed. Comparing SQL should be close enough.
ActiveRecord
- remove all code supporting unsupported versions of Rails (< 6.1)
- add Rails 7.1 to builds
- fix edge failures related to `serialize` method signature
Ruby
- remove all support for rubies < 3.0
- skip multi-thread test on Ruby 3.2+ which is failing for mysterious reasons...
> Update Ruby & Rails versions on CI and fix Sequel spec failures

- .github/workflows/ci.yml
The v3 change originally made in mid-2023 was just merged, but now those are deprecated.  Update to v4.
> Fix the Node v16 deprecation by updating actions to v4

- lib/mobility/plugins/active_model/dirty.rb
- spec/mobility/plugins/active_model/dirty_spec.rb
- spec/mobility/plugins/active_record/dirty_spec.rb
since Rails 6.1 they accept kwargs `from` and `to`, see https://github.com/rails/rails/commit/a6841c720ad567d28a5ffac945bce8acc8b66c1a
> fix active model `*_previously_changed?` and active record `will_save_change_to_*?` and `saved_change_to_*?` dirty methods to accept kwargs

- lib/mobility/plugins/active_record/query.rb
This fixes the issue discussed here https://github.com/shioyama/mobility/pull/654#issuecomment-2503479112,  https://github.com/shioyama/mobility/issues/652#issuecomment-2502206995 and https://github.com/shioyama/mobility/pull/653#issuecomment-2502193696
> I think this caused the second issue with Rails 8.0 and the AS statement with counts not getting wrapped correctly: https://github.com/rails/rails/commit/ba468db0bdc880c694df091b5800d114e963eff0
>
> Previously we got the `Arel::Nodes` for `column_name` in `execute_simple_calculation`. With Rails 8 we actually get just the string `"article_translations_en"."title" AS __mobility_title_en__,` (https://github.com/rails/rails/blob/8-0-stable/activerecord/lib/active_record/relation/calculations.rb#L445)
>
> This is why the `count` in …
> Fix broken count statements in Active Record 8.0

- lib/rails/generators/mobility/templates/initializer.rb
The previous sample code passed a block to the fallbacks method. Instead, they should be an argument.
> Fix fallback syntax in initializer example

- CHANGELOG.md
- lib/mobility/version.rb
With support for ActiveRecord 8.
There's a warning in the gemspec related to #535, it's been in the release candidates for like 2 years now, I think we can release :joy:
> Release 1.3.0

- lib/mobility/plugins/active_record/query.rb
- spec/support/shared_examples/querying_examples.rb
https://github.com/shioyama/mobility/pull/655 fixed an issue with failing querying tests in AR 8, but as it turns out test coverage was incomplete and the fix has introduced breakage to `select` when used without `order`.
I added a small expectation which removes the `order` on part of existing querying tests, and tests now fail on master. Removing the fix from https://github.com/shioyama/mobility/pull/655, they pass (but others fail on AR 8).
The change in Rails was this commit: https://github.com/rails/rails/commit/ba468db0bdc880c694df091b5800d114e963eff0
cc @jukra @n-rodriguez 
We now have a broken state on master.
> Fix for Rails 8 query issue breaks `select` with no `order` clause

- lib/mobility/backends/active_record/pg_hash.rb
- spec/integration/active_record_compatibility_spec.rb
When assigning attribute (which uses translations) nil value, it won't invalidate cache and will store previous value.
This possibly can affect any logic, but the common example is ActiveRecord validations. As cache uses previous value, it will pass presence validation, but it is incorrect as current value is nil.
Disabling cache for the attribute fixes situation, but actually it is not a solution.
This change appeared after version 1.2.9 and possibly after implementing logic for the Issue https://github.com/shioyama/mobility/issues/535
> Issue #664 | Update handling nil value for PgHash

- Gemfile
Builds running AR 7.0 are currently failing, for reasons unrelated to Mobility. This should fix it.
> Fix builds with ActiveRecord 7.0
