lib/mobility/backend/active_record.rb, lib/mobility/backend/active_record/column/query_methods.rb, lib/mobility/backend/active_record/hstore/query_methods.rb, lib/mobility/backend/active_record/jsonb/query_methods.rb, lib/mobility/backend/active_record/key_value/query_methods.rb, lib/mobility/backend/active_record/query_methods.rb, lib/mobility/backend/active_record/serialized/query_methods.rb, lib/mobility/backend/active_record/table/query_methods.rb, lib/mobility/backend/sequel.rb, spec/mobility/backend/active_record/key_value_spec.rb
=> Do not memoize scopes/datasets

lib/mobility.rb, spec/mobility_spec.rb
=> Reset memoized backends when duplicating

lib/mobility.rb, spec/mobility_spec.rb
=> Inherit translated attributes into subclasses

Gemfile, spec/generators/rails/mobility/translations_generator_spec.rb
Some generator specs are failing on generator_spec 0.9.4. This should fix them.
=> Fix failing generator specs

lib/mobility/backend/active_record/query_methods.rb, spec/support/shared_examples/querying_examples.rb
Fixes #33 (AR 5.1)
@jonian can you try this branch and confirm it fixes the issue for you?
=> Avoid using respond_to? on relation in query methods

lib/mobility.rb, lib/mobility/backend/active_record/key_value/query_methods.rb, lib/mobility/wrapper.rb, spec/mobility_spec.rb, spec/support/shared_examples/querying_examples.rb
=> Add proper STI support

.travis.yml, Gemfile, README.md, lib/generators/rails/mobility/active_record_migration_compatibility.rb, lib/generators/rails/mobility/backend_generators/base.rb, lib/generators/rails/mobility/generators.rb, lib/generators/rails/mobility/install_generator.rb, lib/generators/rails/mobility/templates/column_translations.rb, lib/generators/rails/mobility/templates/create_string_translations.rb, lib/generators/rails/mobility/templates/create_text_translations.rb, lib/generators/rails/mobility/templates/table_migration.rb, lib/generators/rails/mobility/templates/table_translations.rb, lib/mobility.rb, spec/active_record/schema.rb, spec/generators/rails/mobility/install_generator_spec.rb, spec/generators/rails/mobility/translations_generator_spec.rb, spec/mobility/active_record_compatibility_spec.rb, spec/mobility/backend/active_model/dirty_spec.rb, spec/mobility/backend/active_record/jsonb_spec.rb, spec/mobility/backend/active_record/serialized_spec.rb, spec/spec_helper.rb, spec/support/matchers/indifferent_hash.rb, spec/support/shared_examples/serialization_examples.rb
I've excluded failing specs and added some steps to fix others that were breaking in AR 4.2. There are about 10 specs failing for AR 4.2, but I think it's better to test against the remainder whenever making changes to avoid introducing *new* incompatibilities.
=> Test against AR 4.2

.travis.yml, Gemfile, lib/mobility/backend/sequel/column/query_methods.rb, lib/mobility/backend/sequel/hstore/query_methods.rb, lib/mobility/backend/sequel/jsonb/query_methods.rb, lib/mobility/backend/sequel/key_value/query_methods.rb, lib/mobility/backend/sequel/postgres_query_methods.rb, lib/mobility/backend/sequel/table/query_methods.rb, spec/spec_helper.rb, spec/support/shared_examples/querying_examples.rb
=> Support Sequel >= 4.46

.travis.yml, Gemfile, lib/mobility/backend.rb, lib/mobility/backend/cache.rb, lib/mobility/backend/default.rb, lib/mobility/backend/fallbacks.rb, lib/mobility/backend/null.rb, lib/mobility/backend/presence.rb, lib/mobility/core_ext/string.rb, spec/performance/attributes_spec.rb, spec/performance/configuration_spec.rb, spec/spec_helper.rb, spec/support/matchers/allocate_under.rb
Inspired by: https://blog.honeybadger.io/testing-object-allocations/
=> Test object allocations

lib/mobility.rb, lib/mobility/backends/sequel/serialized.rb, lib/mobility/plugins/default.rb, spec/mobility/attributes_spec.rb, spec/mobility/backends/active_record/column_spec.rb, spec/mobility/backends/active_record/hstore_spec.rb, spec/mobility/backends/active_record/jsonb_spec.rb, spec/mobility/backends/active_record/key_value_spec.rb, spec/mobility/backends/active_record/serialized_spec.rb, spec/mobility/backends/active_record/table_spec.rb, spec/mobility/backends/sequel/column_spec.rb, spec/mobility/backends/sequel/hstore_spec.rb, spec/mobility/backends/sequel/jsonb_spec.rb, spec/mobility/backends/sequel/key_value_spec.rb, spec/mobility/backends/sequel/serialized_spec.rb, spec/mobility/backends/sequel/table_spec.rb, spec/mobility/backends/sequel_spec.rb, spec/mobility/plugins/active_model/dirty_spec.rb, spec/mobility/plugins/active_record/dirty_spec.rb, spec/mobility/plugins/cache_spec.rb, spec/mobility/plugins/sequel/dirty_spec.rb, spec/mobility_spec.rb, spec/performance/attributes_spec.rb
=> Use "extend Mobility" instead of "include Mobility" everywhere

lib/mobility/backends/sequel/pg_hash.rb, spec/mobility/backends/sequel/hstore_spec.rb, spec/mobility/backends/sequel/jsonb_spec.rb
=> Set default values in jsonb/hstore backends

.travis.yml, Gemfile
See: https://stackoverflow.com/questions/44927531/set-version-to-latest-version-including-prereleases-in-gemfile
=> Test against AR prerelease versions and against latest Sequel

lib/mobility/attributes.rb, lib/mobility/configuration.rb, spec/mobility/configuration_spec.rb, spec/performance/attributes_spec.rb, spec/performance/configuration_spec.rb
=> Disable setting value of the default_options hash directly

lib/mobility/plugins/locale_accessors.rb
I noticed FallthroughAccessors does this.
=> Use public_send in locale_accessors plugin

lib/mobility/plugins/default.rb, spec/mobility/plugins/default_spec.rb
=> Pass locale and options to Proc in default plugin

lib/mobility/backends/active_record/key_value/query_methods.rb, lib/mobility/backends/active_record/pg_query_methods.rb, lib/mobility/backends/active_record/table/query_methods.rb, lib/mobility/backends/sequel/pg_query_methods.rb, spec/mobility/backends/active_record/table_spec.rb, spec/support/shared_examples/querying_examples.rb
Fixes #90
Currently breaking with jsonb + hstore backends (as expected).
=> Handle array of values to translated attribute query

lib/mobility/backends/active_record/table.rb, spec/mobility/backends/active_record/table_spec.rb
Fixes #100
@pwim Have a look when you have a chance.
=> Do not save blank translations in AR Table backend

lib/mobility/active_record.rb, lib/mobility/active_record/uniqueness_validator.rb, spec/mobility/active_record_spec.rb
=> Warn user if case_sensitive option is passed to uniqueness validator on translated attributes

CHANGELOG.md, lib/mobility/plugins/active_record/dirty.rb, spec/mobility/plugins/active_record/dirty_spec.rb, spec/mobility/plugins/dirty_spec.rb
=> Make _read_attribute public in AR Dirty plugin

.codeclimate.yml, Gemfile, benchmarks/overhead.rb, lib/mobility.rb, lib/mobility/attributes.rb
Some small changes to improve performance, and a benchmark test borrowed from Traco.
=> Benchmark to improve performance

lib/mobility/backends/hash_valued.rb, lib/mobility/backends/null.rb, lib/mobility/backends/sequel/column.rb
Nothing to see here, just some house-cleaning...
=> Reduce object allocations

Gemfile, lib/mobility/backends/active_record/container.rb
=> Add missing container requires

spec/active_record/schema.rb, spec/sequel/schema.rb
=> Use empty jsonb object as column default

lib/mobility/backends/active_record/query_methods.rb
This is much easier to read I think.
=> Refactor Mobility::Backends::AR::QueryMethods using MobilityWhereChain module

lib/mobility/backends/active_record/table.rb
=> Rename in to in_locale

lib/mobility/backends/active_record/key_value.rb, lib/mobility/backends/key_value.rb, lib/mobility/backends/sequel/key_value.rb, lib/rails/generators/mobility/templates/initializer.rb, spec/active_record/models.rb, spec/mobility/backends/active_record/key_value_spec.rb, spec/mobility/backends/active_record/serialized_spec.rb, spec/mobility/backends/active_record_spec.rb, spec/mobility/backends/key_value_spec.rb, spec/mobility/backends/sequel/key_value_spec.rb, spec/mobility/backends/sequel/serialized_spec.rb, spec/mobility/backends/sequel_spec.rb, spec/sequel/models.rb, spec/spec_helper.rb
=> Require specifying type for KeyValue backends

lib/mobility/attributes.rb, lib/mobility/backend.rb, lib/mobility/backends/active_record/container.rb, lib/mobility/backends/active_record/hstore.rb, lib/mobility/backends/active_record/json.rb, lib/mobility/backends/active_record/jsonb.rb, lib/mobility/backends/hash_valued.rb, lib/mobility/backends/key_value.rb, lib/mobility/backends/sequel/container.rb, lib/mobility/backends/sequel/hstore.rb, lib/mobility/backends/sequel/json.rb, lib/mobility/backends/sequel/jsonb.rb, lib/mobility/backends/sequel/key_value.rb, lib/mobility/backends/sequel/table.rb, lib/mobility/backends/table.rb, lib/mobility/plugins/cache.rb, lib/mobility/translates.rb, spec/mobility/attributes_spec.rb, spec/mobility/backend_spec.rb, spec/mobility/backends/active_record/column_spec.rb, spec/mobility/backends/sequel/column_spec.rb, spec/mobility/plugins/default_spec.rb, spec/mobility/plugins/fallbacks_spec.rb, spec/support/shared_examples/backend_examples.rb
=> Define options on subclassed backend class

mobility.gemspec
Since 2.2.x is no longer supported.
=> Require Ruby version 2.3.7 or greater

lib/mobility.rb, spec/integration/active_record_compatibility_spec.rb
=> Fix uniqueness on Mobility model with no translated attributes

lib/mobility/attributes.rb, lib/mobility/plugins/active_record/query.rb, spec/mobility/attributes_spec.rb, spec/support/shared_examples/querying_examples.rb
=> Support order clause on translated queries

lib/mobility/backends/sequel/key_value.rb, lib/mobility/backends/sequel/table.rb
=> Default Sequel Table/KeyValue backends to OUTER join

lib/mobility/plugins/fallthrough_accessors.rb, spec/mobility/plugins/fallthrough_accessors_spec.rb
Related: #294
My goal here is to make all plugins simple modules.
=> Simplify FallthroughAccessors plugin

lib/mobility/backends/active_record/container.rb, spec/mobility/backends/active_record/container_spec.rb
=> Load column_type when building node

lib/mobility.rb, lib/mobility/backends/key_value.rb, lib/mobility/configuration.rb, spec/mobility/backends/key_value_spec.rb, spec/mobility/configuration_spec.rb, spec/mobility_spec.rb
=> Remove deprecated methods

.travis.yml, Gemfile
Sometimes version bumps trip things up, let's just make sure everything is working smoothly as of the latest version of Rails.
=> Test against ActiveRecord 6.0

lib/mobility/active_record/translation.rb
=> Enforce case_sensitive comparison for rails 6.1

lib/mobility/arel/visitor.rb
=> Accept any number of arguments to Arel::Visitors::Visitor#visit #338

.codeclimate.yml, .travis.yml, Gemfile, lib/mobility/plugins/active_model/dirty.rb, lib/mobility/plugins/active_record/dirty.rb, spec/mobility/plugins/active_model/dirty_spec.rb, spec/mobility/plugins/active_record/dirty_spec.rb, spec/spec_helper.rb
Fixes #323
See my [comment below](https://github.com/shioyama/mobility/pull/343#issuecomment-544369012) for a summary of changes.
=> Fix Dirty plugin with Rails 6

.codeclimate.yml, .travis.yml, Gemfile, spec/spec_helper.rb
Let's just get this out of the way first.
=> Sync small changes from master to 0-8-stable

lib/mobility/plugins/active_model/dirty.rb, lib/mobility/plugins/active_record/dirty.rb, spec/mobility/plugins/active_model/dirty_spec.rb
This PR includes a few more fixes/improvements to the dirty plugin.
=> More dirty fixes

spec/generators/rails/mobility/translations_generator_spec.rb
Ref: https://github.com/shioyama/mobility/pull/357#issuecomment-577650913
=> Fix Thor deprecation error in spec

.github/workflows/ci.yml
Travis has failed me for the last time. Let's make the switch.
=> Switch to Github Actions for CI

.github/workflows/ci.yml, Gemfile, Rakefile, spec/active_record/schema.rb, spec/database.rb, spec/databases.yml, spec/mobility/plugins/fallbacks_spec.rb, spec/spec_helper.rb
=> Update Gemfile to work with Github Actions

CHANGELOG.md, lib/mobility/version.rb, mobility.gemspec, spec/mobility_spec.rb
Following the example of many other gems.
=> Define gem version cleanly

lib/mobility/plugin.rb, lib/mobility/plugins/active_record/query.rb
=> Small fixes

lib/mobility/plugin.rb, spec/mobility/plugin_spec.rb
The `depends_on :foo, include: false` pattern is a bit tricky. It basically says that one plugin depends on another one, but not to actually include it, only check to see if it has been included (elsewhere) before running its initialize/included hooks.
This is a way to support optional dependencies, where a certain plugin is triggered by conditions being satisfied. This will help clean up a lot of stuff, but still not quite sure if the API is sensible or if it could be made easier to understand... :thinking:
It's confusing enough that I myself implemented it wrong (and tested it wrong) in #409.
=> Fix include: false on depends_on

spec/spec_helper.rb, spec/support/shared_examples/backend_examples.rb
See https://github.com/shioyama/mobility/pull/435/files#issuecomment-682275777 for context.
=> Fix constant loading issues in specs for AR 6.1

lib/mobility/plugins/backend.rb
=> Allow nil backend

spec/sequel/schema.rb
=> Remove unused test table

lib/mobility/plugins/active_record/query.rb, lib/mobility/plugins/sequel/query.rb
=> Ensure backend is set in query plugin

README.md, lib/mobility.rb, lib/mobility/backend.rb, lib/mobility/backends/active_record/table.rb, lib/mobility/backends/key_value.rb, lib/mobility/translations.rb
Finally! Just cleaning up a few things and we'll start with a first alpha release. For anyone who is following, I've started a wiki page on v1.0 [here](https://github.com/shioyama/mobility/wiki/Introduction-to-Mobility-v1.0).
=> Release 1.0.0.alpha

lib/mobility/backends/table.rb
Noticed warnings about this on Spina (https://github.com/SpinaCMS/Spina/pull/627).
=> Only fetch translations from cache if variable is initialized

.github/workflows/ci.yml
v2 increases speed of caching and reduces size
https://github.com/actions/cache/releases
=> Use cache v2 in CI

CHANGELOG.md, lib/mobility/plugins/attributes.rb, spec/mobility/translations_spec.rb
This is never used internally and has little value externally, let's remove it.
=> Remove Plugins::Attributes#each

lib/mobility.rb
Related: https://github.com/shioyama/friendly_id-mobility/pull/26/files#r548523113
=> Check that Rails.respond_to?(:application)

spec/mobility/plugins/sequel/query_spec.rb
Gotta be more careful not to let these slip through...
=> Remove focus:true

lib/mobility/backends/key_value.rb, lib/mobility/backends/sequel/key_value.rb, spec/mobility/backends/sequel/key_value_spec.rb
Port #488 to Sequel. Also, prefer `__send__` over `send`.
This is mostly just for completeness, so the code is consistent.
=> Add key, value and belongs_to options to Sequel key-value backend

lib/mobility.rb, spec/mobility_spec.rb
=> Fix Mobility.default_backend

.github/workflows/ci.yml, CHANGELOG.md, README.md, lib/mobility/plugins/backend.rb, lib/mobility/version.rb, spec/mobility/plugins/backend_spec.rb
Fixes #492.
I'll deploy this as 1.0.4
=> Correctly override default backend options (1-0 branch)

lib/mobility/backends/active_record/table.rb, spec/mobility/backends/active_record/key_value_spec.rb, spec/mobility/backends/active_record/table_spec.rb
=> Fix duping with table backend

lib/mobility/backends/active_record/table.rb, spec/mobility/backends/active_record/key_value_spec.rb, spec/mobility/backends/active_record/table_spec.rb
Same as #499 but against 1-0 branch, for release as 1.0.5
=> Fix duping with table backend (1-0 branch)

lib/mobility/plugins/active_record.rb, lib/mobility/plugins/active_record/column_fallback.rb, lib/mobility/plugins/column_fallback.rb, lib/mobility/plugins/sequel.rb, lib/mobility/plugins/sequel/column_fallback.rb, spec/mobility/plugins/active_record/column_fallback_spec.rb, spec/mobility/plugins/sequel/column_fallback_spec.rb
Solves: #335
I wanted to see if this would work, and it does! This works like #335 but supports any backend. (Only lightly tested mind you.)
@mattboldt if you have time, have a look. I think with some tests and a bit of effort to work out the edge cases, this could be a really great new plugin. A lot of people want this.
=> ColumnFallback plugin to fallback to original column

lib/mobility/plugins/active_record/column_fallback.rb, lib/mobility/plugins/sequel/column_fallback.rb
I totally over-complicated this.
=> Refactor ColumnFallback plugin

CHANGELOG.md, lib/mobility/plugins/fallbacks.rb
I realized we can avoid using a module builder here, which improves the performance of `read` method dispatch.
=> Simplify Fallbacks plugin

lib/mobility/backends/sequel/container.rb
Ref: https://github.com/jeremyevans/sequel/commit/c4ae5d42e5
=> Fix Seuqel container op in Sequel

lib/mobility/backends/active_record/key_value.rb, lib/mobility/backends/active_record/table.rb
=> Fix #541: Support primary keys other then :id on model classes

.github/workflows/ci.yml, CHANGELOG.md, README.md, lib/mobility/plugins/fallbacks.rb, lib/mobility/version.rb
This fixes #544 for the 1-2 branch.
=> Fix fallbacks performance regression (1-2 branch)

CHANGELOG.md, README.md, lib/mobility/plugins/fallbacks.rb
This is an attempt to fix https://github.com/shioyama/mobility/issues/544
@f1sherman can you try this branch?
=> Fix fallbacks performance regression

lib/rails/generators/mobility/backend_generators/base.rb
See: https://github.com/shioyama/mobility/issues/549
Also: https://github.com/bensheldon/good_job_rails7/issues/2
=> Avoid referencing ActiveRecord::Base

mobility.gemspec
=> Require mfa on rubygems

lib/mobility/plugins/active_record/query.rb, lib/mobility/plugins/sequel/query.rb, spec/mobility/plugins/active_record/query_spec.rb, spec/mobility/plugins/sequel/query_spec.rb
=> Do not query same attribute more than once

lib/mobility/plugins/active_record/query.rb, lib/mobility/plugins/sequel/query.rb, spec/mobility/plugins/active_record/query_spec.rb, spec/mobility/plugins/sequel/query_spec.rb
Same as #577, but for 1-2 branch.
=> Do not query same attribute more than once (1-2 branch)

lib/mobility/plugins/backend.rb, spec/mobility/plugins/backend_spec.rb
https://github.com/shioyama/mobility/pull/568 for 1-2 branch
=> Fix sti subclassing (1-2 branch)

lib/mobility/plugins/active_record/query.rb, spec/mobility/plugins/active_record/query_spec.rb
Replaces #582
Fixes #513 in Rails 7
=> Fix for #513 with select on Rails 7.x

lib/mobility/plugins/active_record/query.rb, spec/mobility/plugins/active_record/query_spec.rb
https://github.com/shioyama/mobility/pull/583 for 1-2 branch.
=> Fix for #513 with select on Rails 7.x (1-2 branch)

README.md
Motivation and history: https://github.com/shioyama/mobility/issues/618
=> Add mobility_typed plugin reference to README

lib/mobility/backends/active_record/table.rb, spec/mobility/backends/active_record/table_spec.rb
=> allow compound foreign keys

.github/workflows/ci.yml, Gemfile, lib/mobility/plugins/active_record/query.rb
=> Update CI config, add support for Rails 8

.github/workflows/ci.yml, CHANGELOG.md, README.md, lib/mobility/backends/active_record/container.rb, lib/mobility/plugins/active_record/dirty.rb, lib/mobility/plugins/active_record/query.rb, lib/mobility/plugins/arel/nodes/pg_ops.rb, spec/integration/active_record_compatibility_spec.rb, spec/mobility/backends/active_record/container_spec.rb, spec/mobility/backends/active_record/json_spec.rb, spec/mobility/backends/active_record/jsonb_spec.rb, spec/mobility/backends/active_record/serialized_spec.rb, spec/mobility/plugins/active_model/dirty_spec.rb, spec/mobility/plugins/active_record/dirty_spec.rb, spec/support/shared_examples/querying_examples.rb
These conditionals have been here waaaay too long. Rails < 7.0 and Ruby < 3.1 are EOL.
=> Only support Rails >= 7.0 and Ruby >= 3.1
